historic_cards = [
"+2 Mace",
"Abandon the Post",
"Aberrant Mind Sorcerer",
"Abiding Grace",
"Abnormal Endurance",
"Abomination of Llanowar",
"Abrade",
"Absorb Identity",
"Abundant Harvest",
"Abzan Battle Priest",
"Abzan Falconer",
"Academic Dispute",
"Academy Drake",
"Academy Journeymage",
"Access Tunnel",
"Accursed Horde",
"Acolyte of Affliction",
"Acquisitions Expert",
"Act of Treason",
"Adamant Will",
"Adanto Vanguard",
"Adaptive Shimmerer",
"Adaptive Snapjaw",
"Adeliz, the Cinder Wind",
"Adherent of Hope",
"Adventure Awaits",
"Adventurous Impulse",
"Aegar, the Freezing Flame",
"Aegis of the Heavens",
"Aegis Turtle",
"Aerial Assault",
"Aerial Engineer",
"Aerial Guide",
"Aerial Responder",
"Aeromoeba",
"Aeromunculus",
"Aeronaut Admiral",
"Aesthir Glider",
"Aether Chaser",
"Aether Gust",
"Aether Helix",
"Aether Hub",
"Aether Inspector",
"Aether Meltdown",
"Aether Poisoner",
"Aether Spellbomb",
"Aether Swooper",
"Aether Theorist",
"Aether Tradewinds",
"Aether Tunnel",
"Aetherborn Marauder",
"Aethershield Artificer",
"Aetherstream Leopard",
"Aethertorch Renegade",
"Affa Guard Hound",
"Affectionate Indrik",
"Ageless Guardian",
"Aggressive Urge",
"Agonizing Remorse",
"Agonizing Syphon",
"Ahn-Crop Champion",
"Ahn-Crop Crasher",
"Ahn-Crop Invader",
"Aid the Fallen",
"Aim for the Head",
"Ainok Bond-Kin",
"Air Elemental",
"Air-Cult Elemental",
"Airdrop Aeronauts",
"Ajani's Pridemate",
"Ajani's Welcome",
"Akoum Hellhound",
"Akoum Warrior",
"Alabaster Mage",
"Alchemist's Gift",
"Alchemist's Greeting",
"Alchemist's Retrieval",
"Alert Heedbonder",
"Alirios, Enraptured",
"All That Glitters",
"Alley Evasion",
"Alley Strangler",
"Allied Assault",
"Alloy Myr",
"Alluring Suitor",
"Almighty Brushwagg",
"Alpine Houndmaster",
"Alpine Meadow",
"Alpine Watchdog",
"Alseid of Life's Bounty",
"Altar of the Goyf",
"Altar of the Pantheon",
"Amaranthine Wall",
"Ambassador Oak",
"Ambitious Farmhand",
"Amorphous Axe",
"Anax, Hardened in the Forge",
"Ancestral Anger",
"Ancestral Blade",
"Ancestral Mask",
"Ancestral Statue",
"Ancient Animus",
"Ancient Brontodon",
"Ancient Crab",
"Ancient Grudge",
"Ancient Lumberknot",
"Ancient Ziggurat",
"Angel of Mercy",
"Angel of the Dawn",
"Angel of the God-Pharaoh",
"Angel of Unity",
"Angel of Vitality",
"Angelheart Protector",
"Angelic Ascension",
"Angelic Edict",
"Angelic Exaltation",
"Angelic Gift",
"Angelic Page",
"Angelic Purge",
"Angelic Quartermaster",
"Angelic Reward",
"Angrath, Captain of Chaos",
"Angrath's Ambusher",
"Angrath's Rampage",
"Animating Faerie",
"Annul",
"Anointed Chorister",
"Anointed Deacon",
"Anointer of Valor",
"Anointer Priest",
"Anticipate",
"Anticognition",
"Anvilwrought Raptor",
"Apostle of Purifying Light",
"Appeal /// Authority",
"Appetite for the Unnatural",
"Applied Biomancy",
"Apprentice Sharpshooter",
"Aquatic Incursion",
"Arachnoform",
"Arbor Armament",
"Arborback Stomper",
"Arborea Pegasus",
"Arboreal Grazer",
"Arboretum Elemental",
"Arcane Encyclopedia",
"Arcane Flight",
"Arcane Infusion",
"Arcane Investigator",
"Arcane Signet",
"Arcane Subtraction",
"Arcanist's Owl",
"Arcbound Mouser",
"Arcbound Prototype",
"Arcbound Shikari",
"Arcbound Slasher",
"Arcbound Tracker",
"Arcbound Whelp",
"Archaeomender",
"Archfiend of Sorrows",
"Archfiend's Vessel",
"Archghoul of Thraben",
"Archipelagore",
"Archon of Absolution",
"Archon of Falling Stars",
"Archway Angel",
"Archway Commons",
"Arctic Treeline",
"Arcus Acolyte",
"Ardent Dustspeaker",
"Ardent Electromancer",
"Ardent Elementalist",
"Ardenvale Paladin",
"Ardenvale Tactician",
"Arena Trickster",
"Arisen Gorgon",
"Arlinn, Voice of the Pack",
"Arlinn's Wolf",
"Arm the Cathars",
"Armed and Armored",
"Armorcraft Judge",
"Armored Whirl Turtle",
"Armory Veteran",
"Arni Slays the Troll",
"Arrester's Admonition",
"Arrester's Zeal",
"Arrogant Outlaw",
"Arrogant Poet",
"Arterial Flow",
"Artful Takedown",
"Artificer's Assistant",
"Arvad the Cursed",
"Ascent of the Worthy",
"Ashiok, Dream Render",
"Ashiok's Skulker",
"Ashmouth Hound",
"Aspect of Lamprey",
"Aspect of Manticore",
"Assassin's Strike",
"Assault Formation",
"Attendant of Vraska",
"Attended Healer",
"Attune with Aether",
"Atzocan Archer",
"Atzocan Seer",
"Audacious Infiltrator",
"Audacious Thief",
"Auger Spree",
"Augur of Bolas",
"Augury Raven",
"Auspicious Starrix",
"Avalanche Caller",
"Aven Eternal",
"Aven Gagglemaster",
"Aven Initiate",
"Aven Mindcensor",
"Aven of Enduring Hope",
"Aven Sentry",
"Aven Wind Guide",
"Aven Wind Mage",
"Avian Oddity",
"Aviary Mechanic",
"Aviation Pioneer",
"Awaken the Bear",
"Awakener Druid",
"Axebane Beast",
"Axgard Armory",
"Axgard Braggart",
"Axgard Cavalry",
"Azorius Guildgate",
"Azorius Knight-Arbiter",
"Azorius Locket",
"Azorius Skyguard",
"Azra Smokeshaper",
"Back for More",
"Bad Deal",
"Baffling Defenses",
"Baffling End",
"Bag of Holding",
"Baird, Steward of Argive",
"Baithook Angler",
"Bake into a Pie",
"Bala Ged Recovery",
"Baleful Ammit",
"Baleful Beholder",
"Ballista Charger",
"Ballista Watcher",
"Baloth Gorger",
"Baloth Packhunter",
"Band Together",
"Baneblade Scoundrel",
"Banehound",
"Banishing Light",
"Bankrupt in Blood",
"Bannerhide Krushok",
"Bar the Gate",
"Barbarian Class",
"Barbed Spike",
"Barge In",
"Barging Sergeant",
"Barkhide Troll",
"Barony Vampire",
"Barrage of Expendables",
"Barren Moor",
"Barricade Breaker",
"Barrier Breach",
"Barrier of Bones",
"Barrow Witches",
"Barrowin of Clan Undurr",
"Barter in Blood",
"Bartered Cow",
"Bartizan Bats",
"Basalt Ravager",
"Base Camp",
"Basilica Bell-Haunt",
"Basri's Acolyte",
"Basri's Solidarity",
"Bastion Enforcer",
"Bastion Mastodon",
"Bastion of Remembrance",
"Bat Whisperer",
"Bathe in Dragonfire",
"Battalion Foot Soldier",
"Batterbone",
"Battering Krasis",
"Battershield Warrior",
"Battle Cry Goblin",
"Battle Screech",
"Battle Squadron",
"Battle-Rattle Shaman",
"Battlefield Promotion",
"Battlefield Raptor",
"Battlefield Scavenger",
"Battleground Geist",
"Bayou Groff",
"Beacon Bolt",
"Beaming Defiance",
"Beamsplitter Mage",
"Beanstalk Giant",
"Bear Cub",
"Bearded Axe",
"Beetleback Chief",
"Befuddle",
"Behold the Multiverse",
"Belle of the Brawl",
"Belligerent Brontodon",
"Belligerent Guest",
"Belligerent Sliver",
"Bellowing Aegisaur",
"Belltower Sphinx",
"Beloved Beggar",
"Beloved Princess",
"Benalish Honor Guard",
"Beneath the Sands",
"Bereaved Survivor",
"Berg Strider",
"Beskir Shieldmate",
"Bestial Menace",
"Beyeen Veil",
"Biblioplex Assistant",
"Big Play",
"Bind the Monster",
"Binding Geist",
"Binding Mummy",
"Binding the Old Gods",
"Biogenic Upgrade",
"Biolume Egg",
"Biomathematician",
"Bird Admirer",
"Birthing Boughs",
"Bishop of the Bloodstained",
"Bishop's Soldier",
"Bitterbow Sharpshooters",
"Black Cat",
"Black Dragon",
"Blackbloom Rogue",
"Blade Banish",
"Blade Instructor",
"Blade Juggler",
"Bladeback Sliver",
"Bladebrand",
"Bladestitched Skaab",
"Bladewing the Risen",
"Blanchwood Armor",
"Blazing Hope",
"Blazing Rootwalla",
"Blazing Volley",
"Bleed Dry",
"Bleeding Edge",
"Blessed Defiance",
"Blessed Light",
"Blessed Spirits",
"Blessing of Belzenlok",
"Blight Keeper",
"Blight-Breath Catoblepas",
"Blightbeetle",
"Blighted Bat",
"Blindblast",
"Blinding Fog",
"Blink Dog",
"Blink of an Eye",
"Blisterspit Gremlin",
"Blisterstick Shaman",
"Blitz Leech",
"Blitz of the Thunder-Raptor",
"Blizzard Brawl",
"Blood Age General",
"Blood Artist",
"Blood Aspirant",
"Blood Beckoning",
"Blood Burglar",
"Blood Curdle",
"Blood Divination",
"Blood for Bones",
"Blood Fountain",
"Blood Glutton",
"Blood Host",
"Blood Hypnotist",
"Blood Pact",
"Blood Petal Celebrant",
"Blood Price",
"Blood Researcher",
"Blood Servitor",
"Bloodbond Vampire",
"Bloodchief's Thirst",
"Bloodcrazed Socialite",
"Bloodfell Caves",
"Bloodhaze Wolverine",
"Bloodhunter Bat",
"Bloodline Pretender",
"Bloodlust Inciter",
"Bloodmist Infiltrator",
"Bloodrage Brawler",
"Bloodrock Cyclops",
"Bloodshot Trainee",
"Bloodsky Berserker",
"Bloodsoaked Altar",
"Bloodstone Goblin",
"Bloodsworn Squire",
"Bloodtallow Candle",
"Bloodthirsty Aerialist",
"Bloodtithe Collector",
"Bloodtithe Harvester",
"Bloody Betrayal",
"Bloom Hulk",
"Blossom Dryad",
"Blossoming Defense",
"Blossoming Sands",
"Blow Your House Down",
"Blue Dragon",
"Blur of Blades",
"Blur Sliver",
"Board the Weatherlight",
"Boarded Window",
"Bog Naughty",
"Bogardan Dragonheart",
"Bogbrew Witch",
"Boggart Brute",
"Bogstomper",
"Bojuka Bog",
"Bolrac-Clan Crusher",
"Bolt Bend",
"Bolt Hound",
"Bomat Bazaar Barge",
"Bombard",
"Bond of Discipline",
"Bond of Flourishing",
"Bond of Insight",
"Bond of Passion",
"Bond of Revival",
"Bonded Construct",
"Bonded Horncrest",
"Bonds of Faith",
"Bone Picker",
"Bone Pit Brute",
"Bone Shards",
"Bone Splinters",
"Bone to Ash",
"Boneclad Necromancer",
"Bonesplitter",
"Boneyard Aberration",
"Boneyard Lurker",
"Bontu's Monument",
"Book Devourer",
"Bookwurm",
"Boon of the Wish-Giver",
"Boot Nipper",
"Boots of Speed",
"Borderland Marauder",
"Borderland Minotaur",
"Boreal Elemental",
"Boreal Outrider",
"Boros Challenger",
"Boros Elite",
"Boros Guildgate",
"Boros Locket",
"Borrowed Time",
"Bound in Gold",
"Bounding Wolf",
"Bounty of the Deep",
"Brackish Trudge",
"Brain Maggot",
"Bramble Armor",
"Bramble Wurm",
"Bramblefort Fink",
"Brawl-Bash Ogre",
"Brazen Buccaneers",
"Brazen Dwarf",
"Brazen Freebooter",
"Breaching Hippocamp",
"Break Expectations",
"Breakneck Berserker",
"Breathless Knight",
"Bred for the Hunt",
"Bretagard Stronghold",
"Bride's Gown",
"Bright Reprisal",
"Brightmare",
"Brightwood Tracker",
"Brimstone Trebuchet",
"Brimstone Vandal",
"Brindle Shoat",
"Brine Comber",
"Brine Giant",
"Brinebarrow Intruder",
"Brineborn Cutthroat",
"Bring to Trial",
"Bristling Boar",
"Brittle Blast",
"Broken Bond",
"Broken Wings",
"Bronze Sword",
"Brood Weaver",
"Bruenor Battlehammer",
"Brushfire Elemental",
"Brushstrider",
"Brute Strength",
"Bubble Snare",
"Bubbling Cauldron",
"Buccaneer's Bravado",
"Built to Last",
"Built to Smash",
"Bulette",
"Bull's Strength",
"Bulwark Giant",
"Burdened Aerialist",
"Burglar Rat",
"Buried Ruin",
"Burlfist Oak",
"Burly Breaker",
"Burn Bright",
"Burn the Accursed",
"Burning Hands",
"Burning Prophet",
"Burning-Fist Minotaur",
"Burning-Tree Emissary",
"Burning-Tree Vandal",
"Burning-Yard Trainer",
"Burrog Befuddler",
"Bury in Books",
"Bushmeat Poacher",
"By Force",
"Cabal Evangel",
"Cabal Initiate",
"Cabal Paladin",
"Cacophodon",
"Cadaver Imp",
"Caged Zombie",
"Caligo Skin-Witch",
"Call of the Death-Dweller",
"Call the Cavalry",
"Call to the Feast",
"Callaphe, Beloved of the Sea",
"Callous Dismissal",
"Campus Guide",
"Canal Monitor",
"Cancel",
"Candlegrove Witch",
"Candlelight Vigil",
"Candlelit Cavalry",
"Candletrap",
"Canopy Baloth",
"Canopy Spider",
"Canopy Stalker",
"Canyon Jerboa",
"Captain Ripley Vance",
"Captivating Gyre",
"Captivating Unicorn",
"Capture Sphere",
"Captured by Lagacs",
"Careless Celebrant",
"Carnival // Carnage",
"Carrier Thrall",
"Carrion Grub",
"Carrion Imp",
"Cartographer's Survey",
"Cartouche of Ambition",
"Cartouche of Knowledge",
"Cartouche of Solidarity",
"Cartouche of Strength",
"Cartouche of Zeal",
"Carven Caryatid",
"Cascade Seer",
"Cast Down",
"Cast Out",
"Castaway's Despair",
"Catacomb Crocodile",
"Catalyst Elemental",
"Catapult Fodder",
"Cathar Commando",
"Cathar's Call",
"Cathar's Companion",
"Cathartic Pyre",
"Cathartic Reunion",
"Cauldron Familiar",
"Cauldron's Gift",
"Cavalcade of Calamity",
"Cavalry Drillmaster",
"Cavern Whisperer",
"Celestial Enforcer",
"Celestial Messenger",
"Celestial Unicorn",
"Celestus Sanctifier",
"Cemetery Recruitment",
"Censor",
"Centaur Courser",
"Centaur Nurturer",
"Centaur Peacemaker",
"Ceremonial Knife",
"Ceremonious Rejection",
"Cerulean Drake",
"Chain to Memory",
"Chained Brute",
"Chainer's Edict",
"Chainer's Torment",
"Chainweb Aracnir",
"Chainwhip Cyclops",
"Challenger Troll",
"Champion of the Flame",
"Chandra, Novice Pyromancer",
"Chandra's Defeat",
"Chandra's Embercat",
"Chandra's Magmutt",
"Chandra's Outrage",
"Chandra's Pyreling",
"Chandra's Pyrohelix",
"Chandra's Revolution",
"Chandra's Spitfire",
"Chandra's Triumph",
"Changeling Outcast",
"Channeled Force",
"Chaos Channeler",
"Chaplain of Alms",
"Charge",
"Charge of the Forever-Beast",
"Charge Through",
"Charging Badger",
"Charging Monstrosaur",
"Charging Tuskodon",
"Charging War Boar",
"Charity Extractor",
"Charmed Sleep",
"Charmed Stray",
"Chart a Course",
"Chatter of the Squirrel",
"Chatterstorm",
"Check for Traps",
"Checkpoint Officer",
"Chemister's Insight",
"Cherished Hatchling",
"Chief of the Foundry",
"Child of Night",
"Child of the Pack",
"Chill of the Grave",
"Chillbringer",
"Chilling Trap",
"Chittering Harvester",
"Choking Tethers",
"Choose Your Weapon",
"Chromatic Sphere",
"Chrome Courier",
"Chrome Replicator",
"Cinder Barrens",
"Cinder Elemental",
"Cinderclasm",
"Cinderheart Giant",
"Circle of Confinement",
"Circle of the Moon Druid",
"Circuitous Route",
"Citywatch Sphinx",
"Civic Stalwart",
"Claim /// Fame",
"Claim the Firstborn",
"Clamor Shaman",
"Clan Guildmage",
"Clarion Cathars",
"Clarion Spirit",
"Clash of Titans",
"Clattering Augur",
"Clattering Skeletons",
"Cleansing Ray",
"Cleansing Wildfire",
"Clear Shot",
"Clear the Mind",
"Clear the Stage",
"Cleaving Sliver",
"Cleric Class",
"Cleric of Chill Depths",
"Cleric of Life's Bond",
"Clever Conjurer",
"Clever Lumimancer",
"Cliffhaven Kitesail",
"Cliffhaven Sell-Sword",
"Cling to Dust",
"Cloaked Cadet",
"Clockwork Servant",
"Cloister Gargoyle",
"Closing Statement",
"Cloudblazer",
"Cloudkin Seer",
"Cloudpiercer",
"Cloudreader Sphinx",
"Cloudshift",
"Coastal Piracy",
"Cobbled Lancer",
"Cobbled Wings",
"Code of Constraint",
"Codespell Cleric",
"Cogwork Archivist",
"Cogworker's Puzzleknot",
"Cold-Water Snapper",
"Coldsteel Heart",
"Collar the Culprit",
"Collateral Damage",
"Collision // Colossus",
"Colossal Dreadmaw",
"Colossal Majesty",
"Colossal Plow",
"Colossus Hammer",
"Combat Professor",
"Combine Chrysalis",
"Combine Guildmage",
"Command the Storm",
"Command Tower",
"Commanding Presence",
"Commencement of Festivities",
"Commune with Dinosaurs",
"Compelled Duel",
"Compelling Argument",
"Component Collector",
"Compound Fracture",
"Compulsive Research",
"Compulsory Rest",
"Concerted Defense",
"Conclave Cavalier",
"Conclave Guildmage",
"Conclave Mentor",
"Conclave Tribunal",
"Concordia Pegasus",
"Confront the Assault",
"Consecrate // Consume",
"Consider",
"Consign /// Oblivion",
"Consign to the Pit",
"Consulate Skygate",
"Consulate Turret",
"Contact Other Plane",
"Containment Breach",
"Contentious Plan",
"Contortionist Troupe",
"Contraband Kingpin",
"Contract Killing",
"Conviction",
"Convolute",
"Coordinated Charge",
"Coral Commando",
"Coral Merfolk",
"Coralhelm Guide",
"Corpse Churn",
"Corpse Cobble",
"Corpse Hauler",
"Corpse Knight",
"Corpse Traders",
"Corridor Monitor",
"Corrosive Ooze",
"Cosmotronic Wave",
"Costly Plunder",
"Countervailing Winds",
"Countless Gears Renegade",
"Courage in Crisis",
"Courier Bat",
"Court Cleric",
"Court Homunculus",
"Covert Cutpurse",
"Covetous Castaway",
"Covetous Urge",
"Crackling Drake",
"Cradle of Safety",
"Cram Session",
"Crash the Ramparts",
"Crash Through",
"Crashing Drawbridge",
"Crashing Tide",
"Craven Hulk",
"Crawl from the Cellar",
"Crawling Infestation",
"Creative Outburst",
"Creeping Chill",
"Creeping Mold",
"Creeping Trailblazer",
"Crested Herdcaller",
"Critical Hit",
"Crocanura",
"Crocodile of the Crossing",
"Crookclaw Transmuter",
"Crossroads Candleguide",
"Crow of Dark Tidings",
"Cruel Celebrant",
"Cruel Cut",
"Cruel Witness",
"Crush Contraband",
"Crush Dissent",
"Crush the Weak",
"Crushing Canopy",
"Crushing Disappointment",
"Cry of the Carnarium",
"Crypt Lurker",
"Crypt of the Eternals",
"Cryptic Caves",
"Cryptic Serpent",
"Crystacean",
"Crystal Slipper",
"Cult Guildmage",
"Cultivate",
"Cunning Geysermage",
"Cunning Nightbonder",
"Curate",
"Curator's Ward",
"Curiosity",
"Curious Obsession",
"Curious Pair",
"Cursebound Witch",
"Cyclops Electromancer",
"D'Avenant Trapper",
"Daemogoth Woe-Eater",
"Dagger Caster",
"Daggerback Basilisk",
"Daggersail Aeronaut",
"Damping Sphere",
"Dance with Devils",
"Danitha Capashen, Paragon",
"Daredevil Dragster",
"Daring Buccaneer",
"Daring Demolition",
"Daring Saboteur",
"Dark Bargain",
"Dark Inquiry",
"Dark Nourishment",
"Dark Remedy",
"Darkblade Agent",
"Dauntless Aven",
"Dauntless Bodyguard",
"Dauntless Onslaught",
"Dauntless Survivor",
"Dauntless Unity",
"Davriel, Rogue Shadowmage",
"Davriel's Shadowfugue",
"Davriel's Withering",
"Dawn Evangel",
"Dawnbringer Cleric",
"Dawnfeather Eagle",
"Dawnhart Disciple",
"Dawnhart Geist",
"Dawnhart Mentor",
"Dawnhart Rejuvenator",
"Dawnhart Wardens",
"Dawning Angel",
"Dawntreader Elk",
"Daxos, Blessed by the Sun",
"Daybreak Chaplain",
"Daybreak Charger",
"Daybreak Chimera",
"Daybreak Combatants",
"Daysquad Marshal",
"Dazzling Lights",
"Dead Revels",
"Dead Weight",
"Deadeye Brawler",
"Deadeye Plunderers",
"Deadeye Quartermaster",
"Deadeye Rig-Hauler",
"Deadeye Tormentor",
"Deadly Alliance",
"Deadly Brew",
"Deadly Dispute",
"Deadly Visit",
"Deafening Silence",
"Death Wind",
"Death-Priest of Myrkul",
"Death's Approach",
"Deathbloom Thallid",
"Deathbonnet Sprout",
"Deathknell Berserker",
"Deathless Ancient",
"Deathless Knight",
"Deathsprout",
"Debtors' Transport",
"Decisive Denial",
"Declare Dominance",
"Decoction Module",
"Deem Worthy",
"Deep Freeze",
"Deeproot Warrior",
"Deeproot Waters",
"Deepwood Denizen",
"Deface",
"Defend the Campus",
"Defend the Celestus",
"Defenestrate",
"Defiant Greatmaw",
"Defiant Salvager",
"Defiant Strike",
"Deliberate",
"Delver of Secrets",
"Delver's Torch",
"Demogorgon's Clutches",
"Demolish",
"Demolition Stomper",
"Demon Bolt",
"Demon's Disciple",
"Demonic Gifts",
"Demonic Vigor",
"Demotion",
"Demystify",
"Deny the Divine",
"Depart the Realm",
"Departed Deckhand",
"Depose // Deploy",
"Depths of Desire",
"Desert Cerodon",
"Desert of the Fervent",
"Desert of the Glorified",
"Desert of the Indomitable",
"Desert of the Mindful",
"Desert of the True",
"Desert's Hold",
"Despark",
"Desperate Castaways",
"Desperate Farmer",
"Desperate Lunge",
"Destined /// Lead",
"Destiny Spinner",
"Destructive Digger",
"Destructive Tampering",
"Detention Vortex",
"Devious Cover-Up",
"Devkarin Dissident",
"Devoted Grafkeeper",
"Devoted Paladin",
"Devour Intellect",
"Devourer of Memory",
"Devouring Hellion",
"Devouring Light",
"Devouring Tendrils",
"Devout Decree",
"Diamond Knight",
"Diamond Mare",
"Didn't Say Please",
"Die Young",
"Diffusion Sliver",
"Diligent Excavator",
"Dimir Guildgate",
"Dimir Informant",
"Dimir Locket",
"Dimir Spybug",
"Dina, Soul Steeper",
"Dinosaur Hunter",
"Dinosaur Stampede",
"Dinrova Horror",
"Dire Fleet Captain",
"Dire Fleet Hoarder",
"Dire Fleet Interloper",
"Dire Fleet Neckbreaker",
"Dire Fleet Warmonger",
"Dire Tactics",
"Dire Wolf Prowler",
"Direct Current",
"Diregraf Ghoul",
"Diregraf Horde",
"Diregraf Rebirth",
"Diregraf Scavenger",
"Discerning Taste",
"Disciple of the Sun",
"Discordant Piper",
"Discovery // Dispersal",
"Disdainful Stroke",
"Disenchant",
"Disentomb",
"Disfigure",
"Disinformation Campaign",
"Dismal Backwater",
"Dismiss",
"Disperse",
"Displacer Beast",
"Disposal Mummy",
"Dissenter's Deliverance",
"Dissipate",
"Distant Melody",
"Distracting Geist",
"District Guide",
"Dive Down",
"Diver Skaab",
"Divest",
"Divide by Zero",
"Divination",
"Divine Arrow",
"Divine Gambit",
"Divine Smite",
"Divine Verdict",
"Diviner's Lockbox",
"Djeru's Renunciation",
"Djeru's Resolve",
"Djinni Windseer",
"Dogged Pursuit",
"Domri's Ambush",
"Doom Blade",
"Doomed Dissenter",
"Doomed Traveler",
"Doomfall",
"Doomskar Oracle",
"Doomskar Titan",
"Dormant Grove",
"Doublecast",
"Douse in Gloom",
"Douser of Lights",
"Dovin, Hand of Control",
"Dovin's Acuity",
"Dovin's Automaton",
"Dovin's Veto",
"Draconic Disciple",
"Drag to the Underworld",
"Dragon Egg",
"Dragon Fodder",
"Dragon Hatchling",
"Dragon Mage",
"Dragon Mantle",
"Dragon's Approach",
"Dragon's Disciple",
"Dragon's Fire",
"Dragon's Rage Channeler",
"Dragonloft Idol",
"Dragonlord's Servant",
"Dragonspeaker Shaman",
"Drainpipe Vermin",
"Drana's Silencer",
"Drannith Healer",
"Drannith Stinger",
"Draugr Recruiter",
"Draugr Thought-Thief",
"Draugr's Helm",
"Dread Fugue",
"Dread Rider",
"Dreadful Apathy",
"Dreadhorde Twins",
"Dreadhound",
"Dreadlight Monstrosity",
"Dreadmalkin",
"Dreadwurm",
"Dreamshaper Shaman",
"Dreamstalker Manticore",
"Dreamstone Hedron",
"Dreamtail Heron",
"Dregscape Sliver",
"Drey Keeper",
"Drider",
"Drill Bit",
"Drogskol Infantry",
"Drover of the Mighty",
"Drown in the Loch",
"Drownyard Amalgam",
"Drowsing Tyrannodon",
"Drudge Sentinel",
"Druid Class",
"Druid of Horns",
"Druid of the Cowl",
"Dryad Greenseeker",
"Dryad's Revival",
"Dual Shot",
"Dual Strike",
"Dub",
"Duel for Dominance",
"Duelcraft Trainer",
"Dueling Coach",
"Dueling Rapier",
"Dukhara Peafowl",
"Dune Beetle",
"Dungeon Crawler",
"Dungeon Map",
"Durable Coilbug",
"Duress",
"Dusk Charger",
"Dusk Legion Dreadnought",
"Dusk Legion Zealot",
"Duskborne Skymarcher",
"Duskfang Mentor",
"Duskmantle Operative",
"Duskshell Crawler",
"Duskwielder",
"Dutiful Attendant",
"Dwarfhold Champion",
"Dwarven Hammer",
"Dwarven Mine",
"Dwarven Priest",
"Dwarven Reinforcements",
"Dwindle",
"Dwynen's Elite",
"Eager Construct",
"Eager First-Year",
"Earth-Cult Elemental",
"Easy Prey",
"Eaten Alive",
"Eccentric Apprentice",
"Eccentric Farmer",
"Echoing Return",
"Ecstatic Awakener",
"Eddytrail Hawk",
"Edgar's Awakening",
"Edgewall Innkeeper",
"Edifice of Authority",
"Eidolon of Inspiration",
"Eidolon of Philosophy",
"Elaborate Firecannon",
"Elderfang Disciple",
"Elderfang Ritualist",
"Elderleaf Mentor",
"Electric Revelation",
"Electrify",
"Electrolyze",
"Electrostatic Field",
"Elemental Masterpiece",
"Elemental Summoning",
"Elemental Uprising",
"Elfhame Druid",
"Eliminate",
"Elite Arrester",
"Elite Guardmage",
"Elite Headhunter",
"Elite Instructor",
"Elspeth's Nightmare",
"Elturgard Ranger",
"Elusive Krasis",
"Elven Ambush",
"Elven Bow",
"Elvish Rejuvenator",
"Elvish Visionary",
"Emancipation Angel",
"Ember Hauler",
"Embereth Paladin",
"Embereth Shieldbreaker",
"Embraal Bruiser",
"Emergence Zone",
"Emergent Growth",
"Emergent Sequence",
"Emeria Captain",
"Emissary of Sunrise",
"Empyreal Voyager",
"Empyrean Eagle",
"Encampment Keeper",
"Enchanted Carriage",
"End the Festivities",
"Enduring Sliver",
"Enemy of Enlightenment",
"Enforcer Griffin",
"Engineered Might",
"Engulfing Eruption",
"Enhanced Surveillance",
"Enigma Drake",
"Enlarge",
"Enraged Ceratok",
"Enraged Giant",
"Enter the Unknown",
"Enthralling Hold",
"Enthusiastic Study",
"Entomber Exarch",
"Entrancing Lyre",
"Environmental Sciences",
"Ephemerate",
"Epic Downfall",
"Epicure of Blood",
"Epitaph Golem",
"Era of Innovation",
"Erratic Visionary",
"Erstwhile Trooper",
"Escape Protocol",
"Escape Velocity",
"Essence Capture",
"Essence Extraction",
"Essence Flux",
"Essence Infusion",
"Essence Scatter",
"Essence Symbiote",
"Estwald Shieldbasher",
"Etchings of the Chosen",
"Eternal Isolation",
"Eternal of Harsh Truths",
"Eternal Skylord",
"Eternal Taskmaster",
"Eternal Thirst",
"Ethereal Grasp",
"Etherium Spinner",
"Eureka Moment",
"Eutropia the Twice-Favored",
"Everdawn Champion",
"Eviscerate",
"Evolution Sage",
"Evolving Wilds",
"Excavated Wall",
"Excavating Anurid",
"Excavation Elephant",
"Excavation Mole",
"Exclude",
"Exclusion Mage",
"Exemplar of Strength",
"Exhilarating Elocution",
"Expanded Anatomy",
"Expedition Champion",
"Expedition Diviner",
"Expedition Healer",
"Expedition Skulker",
"Expel",
"Expel from Orazca",
"Experimental Overload",
"Explore",
"Explosive Apparatus",
"Explosive Welcome",
"Expose to Daylight",
"Expressive Iteration",
"Exuberant Wolfbear",
"Exultant Skymarcher",
"Eye Collector",
"Eyeblight Assassin",
"Eyekite",
"Eyes Everywhere",
"Eyes of the Beholder",
"Eyetwitch",
"Fabrication Module",
"Face of Divinity",
"Faceless Agent",
"Facet Reader",
"Facevaulter",
"Fading Hope",
"Faerie Duelist",
"Faerie Guidemother",
"Faerie Miscreant",
"Faerie Seer",
"Faerie Vandal",
"Fairgrounds Patrol",
"Fairgrounds Warden",
"Faith of the Devoted",
"Faith's Fetters",
"Faithful Disciple",
"Faithful Mending",
"Faithless Looting",
"Faithless Salvaging",
"Falcon Abomination",
"Falconer Adept",
"Falkenrath Celebrants",
"Falkenrath Noble",
"Falkenrath Perforator",
"Fall of the Impostor",
"Famished Foragers",
"Famished Paladin",
"Fan Bearer",
"Fanatic of Mogis",
"Fanatical Firebrand",
"Fangblade Brigand",
"Farfinder",
"Farideh, Devil's Chosen",
"Farideh's Fireball",
"Farm /// Market",
"Farsight Adept",
"Fast // Furious",
"Fatal Push",
"Fateful End",
"Fates' Reversal",
"Fathom Fleet Boarder",
"Fathom Fleet Cutthroat",
"Fathom Fleet Firebrand",
"Favorable Winds",
"Favored of Iroas",
"Fear of Death",
"Fearful Villager",
"Fearless Fledgling",
"Fearless Halberdier",
"Fearless Liberator",
"Fearless Pup",
"Fearsome Whelp",
"Feat of Resistance",
"Feed the Serpent",
"Feed the Swarm",
"Feign Death",
"Fell Specter",
"Fell Stinger",
"Fell the Pheasant",
"Fen Hauler",
"Fencing Ace",
"Feral Abomination",
"Feral Hydra",
"Feral Invocation",
"Feral Maaka",
"Feral Prowler",
"Feral Roar",
"Ferocious Pup",
"Ferocious Tigorilla",
"Ferocity of the Wilds",
"Fertilid",
"Fervent Paincaster",
"Fervent Strike",
"Festering Mummy",
"Festering Newt",
"Festival Crasher",
"Festive Funeral",
"Fetid Imp",
"Feywild Trickster",
"Field Creeper",
"Field of Ruin",
"Field Research",
"Field Trip",
"Fierce Empath",
"Fierce Retribution",
"Fierce Witchstalker",
"Fiery Cannonade",
"Fiery Finish",
"Fiery Intervention",
"Fiery Temper",
"Fifty Feet of Rope",
"Fight as One",
"Fight with Fire",
"Filigree Attendant",
"Filigree Familiar",
"Final Death",
"Final Flare",
"Final Parting",
"Final Payment",
"Final Reward",
"Find the Path",
"Finishing Blow",
"Fire Elemental",
"Fire Giant's Fury",
"Fire Prophecy",
"Fire Shrine Keeper",
"Fire Urchin",
"Fireblade Artist",
"Fireblade Charger",
"Fireborn Knight",
"Firebrand Archer",
"Firecannon Blast",
"Firefist Adept",
"Fireforger's Puzzleknot",
"Firemind Vessel",
"Firja, Judge of Valor",
"Firmament Sage",
"First Day of Class",
"First Sliver's Chosen",
"First-Sphere Gargantua",
"Fissure Wizard",
"Fists of Flame",
"Flame Channeler",
"Flame Lash",
"Flame Spill",
"Flame Sweep",
"Flame-Blessed Bolt",
"Flameblade Adept",
"Flames of the Firebrand",
"Flames of the Raze-Boar",
"Flare of Faith",
"Flaxen Intruder",
"Fleeting Spirit",
"Fleshbag Marauder",
"Fleshtaker",
"Flicker of Fate",
"Flight of Equenauts",
"Fling",
"Flip the Switch",
"Flood of Recollection",
"Floodhound",
"Floodwaters",
"Flourishing Fox",
"Flourishing Hunter",
"Flower // Flourish",
"Flummoxed Cyclops",
"Flunk",
"Flurry of Horns",
"Flutterfox",
"Flux Channeler",
"Fly",
"Flycatcher Giraffid",
"Footfall Crater",
"Footlight Fiend",
"Forbidden Friendship",
"Forbidding Spirit",
"Forced Landing",
"Forced Worship",
"Foreboding Fruit",
"Foreboding Statue",
"Forerunner of the Coalition",
"Forerunner of the Empire",
"Forerunner of the Heralds",
"Forerunner of the Legion",
"Forest",
"Forever Young",
"Forge Devil",
"Forging the Tyrite Sword",
"Forgotten Cave",
"Forgotten Sentinel",
"Forsake the Worldly",
"Forsaken Sanctuary",
"Fortify",
"Fortifying Draught",
"Fortifying Provisions",
"Fortress Crab",
"Fortuitous Find",
"Foul Orchard",
"Foul Play",
"Foul Watcher",
"Foulmire Knight",
"Foundry Hornet",
"Foundry Inspector",
"Foundry Screecher",
"Foundry Street Denizen",
"Fountain of Renewal",
"Fourth Bridge Prowler",
"Fractal Summoning",
"Fracture",
"Fragmentize",
"Frantic Inventory",
"Frenzied Arynx",
"Frenzied Devils",
"Frenzied Rage",
"Frenzied Raider",
"Frenzied Raptor",
"Fresh-Faced Recruit",
"Fretwork Colony",
"Frilled Deathspitter",
"Frilled Mystic",
"Frilled Sandwalla",
"Frilled Sea Serpent",
"Frillscare Mentor",
"Frogify",
"Frontline Rebel",
"Frost Augur",
"Frost Bite",
"Frost Breath",
"Frost Lynx",
"Frost Trickster",
"Frostpeak Yeti",
"Frostpyre Arcanist",
"Frostveil Ambush",
"Fruit of Tizerus",
"Fry",
"Fully Grown",
"Fuming Effigy",
"Funeral Longboat",
"Funeral Rites",
"Fungal Infection",
"Fungal Plots",
"Fungal Rebirth",
"Funnel-Web Recluse",
"Furious Reprisal",
"Furious Rise",
"Furnace Whelp",
"Furor of the Bitten",
"Furyblade Vampire",
"Fusion Elemental",
"Fynn, the Fangbearer",
"Gaea's Blessing",
"Gaea's Protector",
"Gale Swooper",
"Galedrifter",
"Gallant Cavalry",
"Galloping Lizrog",
"Galvanic Relay",
"Garenbrig Carver",
"Garenbrig Paladin",
"Garenbrig Squire",
"Gargoyle Sentinel",
"Garna, the Bloodflame",
"Garrison Cat",
"Garrison Griffin",
"Garrison Sergeant",
"Garruk's Gorehorn",
"Garruk's Uprising",
"Gate Colossus",
"Gate to the Afterlife",
"Gatebreaker Ram",
"Gatekeeper Gargoyle",
"Gates Ablaze",
"Gates of Istfell",
"Gateway Plaza",
"Gateway Sneak",
"Gauntlets of Light",
"Gavony Dawnguard",
"Gavony Silversmith",
"Gavony Trapper",
"Gearseeker Serpent",
"Gearshift Ace",
"Gearsmith Guardian",
"Gearsmith Prodigy",
"Geistlight Snare",
"Geistwave",
"Gempalm Incinerator",
"Gempalm Polluter",
"General's Enforcer",
"Generous Stray",
"Geomancer's Gambit",
"Get the Point",
"Ghastbark Twins",
"Ghastly Gloomhunter",
"Ghirapur Guide",
"Ghitu Chronicler",
"Ghitu Journeymage",
"Ghitu Lavarunner",
"Ghor-Clan Wrecker",
"Ghost Quarter",
"Ghost-Lit Drifter",
"Ghostform",
"Ghoulcaller's Accomplice",
"Ghoulish Procession",
"Ghoulraiser",
"Giant Growth",
"Giant Opportunity",
"Giant Ox",
"Giant Spider",
"Giant's Amulet",
"Giant's Grasp",
"Giant's Skewer",
"Gideon's Company",
"Gideon's Reproach",
"Gideon's Sacrifice",
"Gideon's Triumph",
"Gift of Estates",
"Gift of Fangs",
"Gift of Growth",
"Gift of Paradise",
"Gift of Strength",
"Gifted Aetherborn",
"Gilded Assault Cart",
"Gilded Cerodon",
"Gilded Light",
"Gilded Sentinel",
"Gilt-Blade Prowler",
"Giltgrove Stalker",
"Gingerbread Cabin",
"Gingerbrute",
"Gird for Battle",
"Glacial Floodplain",
"Glacial Grasp",
"Gladewalker Ritualist",
"Glaive of the Guildpact",
"Glaring Aegis",
"Glass Casket",
"Gleaming Barrier",
"Gleaming Overseer",
"Glimmer Bairn",
"Glimmer of Genius",
"Glimmerbell",
"Glimpse of Freedom",
"Glimpse the Cosmos",
"Glint",
"Glint-Nest Crane",
"Glint-Sleeve Artisan",
"Glittering Frost",
"Gloom Pangolin",
"Gloom Sower",
"Gloom Stalker",
"Glorifier of Dusk",
"Glorious Enforcer",
"Glory Bearers",
"Glowspore Shaman",
"Glowstone Recluse",
"Gluttonous Guest",
"Gnarlback Rhino",
"Gnarled Sage",
"Gnarlid Colony",
"Gnoll Hunter",
"Gnottvold Recluse",
"Gnottvold Slumbermound",
"Go Blank",
"Go for Blood",
"Goatnap",
"Goblin Anarchomancer",
"Goblin Arsonist",
"Goblin Assailant",
"Goblin Assault Team",
"Goblin Banneret",
"Goblin Barrage",
"Goblin Bird-Grabber",
"Goblin Commando",
"Goblin Cratermaker",
"Goblin Electromancer",
"Goblin Gang Leader",
"Goblin Gathering",
"Goblin Gaveleer",
"Goblin Goon",
"Goblin Instigator",
"Goblin Javelineer",
"Goblin Locksmith",
"Goblin Matron",
"Goblin Morningstar",
"Goblin Motivator",
"Goblin Oriflamme",
"Goblin Rally",
"Goblin Ringleader",
"Goblin Ruinblaster",
"Goblin Shortcutter",
"Goblin Smuggler",
"Goblin Trailblazer",
"Goblin Tunneler",
"Goblin Warchief",
"Goblin Wizardry",
"God-Pharaoh's Statue",
"Gods Willing",
"Gods' Hall Guardian",
"Golden Demise",
"Golden Egg",
"Golden Ratio",
"Goldmaw Champion",
"Goldvein Pick",
"Golgari Findbroker",
"Golgari Guildgate",
"Golgari Locket",
"Golgari Raiders",
"Goma Fada Vanguard",
"Good-Fortune Unicorn",
"Goremand",
"Gorging Vulture",
"Gouged Zealot",
"Graceful Restoration",
"Grapeshot",
"Grappling Sundew",
"Grasp of Darkness",
"Grasping Scoundrel",
"Grasping Thrull",
"Grateful Apparition",
"Grave Bramble",
"Gravedigger",
"Gravel-Hide Goblin",
"Graveshifter",
"Gravitic Punch",
"Gray Merchant of Asphodel",
"Grazing Whiptail",
"Great Hall of Starnheim",
"Greataxe",
"Greater Sandwurm",
"Green Dragon",
"Greenwood Sentinel",
"Gretchen Titchwillow",
"Griffin Aerie",
"Griffin Protector",
"Griffin Sentinel",
"Grim Bounty",
"Grim Captain's Call",
"Grim Draugr",
"Grim Initiate",
"Grim Physician",
"Grim Wanderer",
"Grimdancer",
"Grinning Ignus",
"Grisly Ritual",
"Grisly Salvage",
"Gristle Grinner",
"Grizzled Outrider",
"Grizzly Bears",
"Grizzly Ghoul",
"Groom's Finery",
"Grotag Bug-Catcher",
"Grotag Night-Runner",
"Grotesque Demise",
"Grow from the Ashes",
"Growth Cycle",
"Growth Spiral",
"Gruesome Fate",
"Gruesome Scourger",
"Grumgully, the Generous",
"Grunn, the Lonely King",
"Gruul Beastmaster",
"Gruul Guildgate",
"Gruul Locket",
"Gryff Rider",
"Gryffwing Cavalry",
"Guardian Gladewalker",
"Guardian Idol",
"Guardians of Koilos",
"Guiding Voice",
"Guild Globe",
"Guild Summit",
"Guild Thief",
"Guildpact Informant",
"Gust of Wind",
"Gust Walker",
"Gutter Skulker",
"Guttersnipe",
"Guul Draz Mucklord",
"Gyre Engineer",
"Haazda Marshal",
"Haazda Officer",
"Hackrobat",
"Hagi Mob",
"Hagra Constrictor",
"Hailstorm Valkyrie",
"Half-Elf Monk",
"Hall Monitor",
"Hallar, the Firefletcher",
"Hallowed Priest",
"Hama Pashar, Ruin Seeker",
"Hammer Dropper",
"Hampering Snare",
"Hamza, Guardian of Arashin",
"Harald, King of Skemfar",
"Hard Cover",
"Hard Evidence",
"Hardy Veteran",
"Harmonize",
"Harnessed Lightning",
"Harrow",
"Harvesttide Infiltrator",
"Harvesttide Sentry",
"Hashep Oasis",
"Hateful Eidolon",
"Haunted Dead",
"Havoc Devils",
"Havoc Jester",
"Hazardous Conditions",
"Haze of Pollen",
"Hazoret's Monument",
"Headstrong Brute",
"Headwater Sentries",
"Healer of the Glade",
"Healer's Flock",
"Healer's Hawk",
"Healing Grace",
"Heart-Piercer Bow",
"Heartfire",
"Heartfire Immolator",
"Heartless Act",
"Heartless Pillage",
"Heartwarming Redemption",
"Heated Debate",
"Hedgewitch's Mask",
"Hedron Archive",
"Heightened Reflexes",
"Heir of Falkenrath",
"Heirloom Mirror",
"Hekma Sentinels",
"Helica Glider",
"Heliod's Pilgrim",
"Heliod's Punishment",
"Hell Mongrel",
"Hellkite Punisher",
"Hellkite Whelp",
"Henge Walker",
"Herald of Faith",
"Herald of Hadar",
"Herald of the Dreadhorde",
"Herald of the Fair",
"Herald of the Sun",
"Herald's Horn",
"Heraldic Banner",
"Herd Baloth",
"Hero of the Games",
"Hero of the Nyxborn",
"Hero of the Pride",
"Hero of the Winds",
"Hero's Downfall",
"Heroes of the Revel",
"Heroic Reinforcements",
"Heron of Hope",
"Heron-Blessed Geist",
"Hidden Stockpile",
"Hieroglyphic Illumination",
"Hieromancer's Cage",
"Hierophant's Chalice",
"High Alert",
"Highborn Vampire",
"Highland Forest",
"Highland Game",
"Highland Lake",
"Highspire Artisan",
"Highspire Infusion",
"Hijack",
"Hill Giant Herdgorger",
"Hinterland Drake",
"Hired Blade",
"Hired Hexblade",
"Hired Poisoner",
"Historian of Zhalfir",
"Hitchclaw Recluse",
"Hive Stirrings",
"Hoard Robber",
"Hoarding Ogre",
"Hobblefiend",
"Hobbling Zombie",
"Hobgoblin Captain",
"Hollowhead Sliver",
"Homarid Explorer",
"Homestead Courage",
"Homing Lightning",
"Honden of Cleansing Fire",
"Honden of Infinite Rage",
"Honden of Life's Web",
"Honden of Night's Reach",
"Honden of Seeing Winds",
"Honey Mammoth",
"Honeymoon Hearse",
"Honor the God-Pharaoh",
"Honor Troll",
"Honored Crop-Captain",
"Honored Heirloom",
"Hooded Brawler",
"Hookhand Mariner",
"Hope Tender",
"Hordeling Outburst",
"Horizon Scholar",
"Horizon Seeker",
"Hornbash Mentor",
"Hornswoggle",
"Horror of the Broken Lands",
"Hostile Minotaur",
"Hound Tamer",
"House Guildmage",
"Howl of the Hunt",
"Howling Giant",
"Howling Golem",
"Huatli, the Sun's Heart",
"Huatli's Raptor",
"Huatli's Snubhorn",
"Huatli's Spurring",
"Hulking Bugbear",
"Humble Naturalist",
"Humiliate",
"Humongulus",
"Hungry Flames",
"Hungry for More",
"Hungry Ridgewolf",
"Hunt for Specimens",
"Hunt the Weak",
"Hunted Witness",
"Hunter's Edge",
"Hunter's Insight",
"Hunter's Mark",
"Hunting Pack",
"Huntmaster Liger",
"Hurloon Minotaur",
"Hydra's Growth",
"Hypnotic Specter",
"Hypnotic Sprite",
"Hypothesizzle",
"Hyrax Tower Scout",
"Ice Over",
"Ice Tunnel",
"Iceberg Cancrix",
"Icebind Pillar",
"Icehide Troll",
"Ichor Wellspring",
"Ichthyomorphosis",
"Icy Manipulator",
"Idyllic Grange",
"Ifnir Deadlands",
"Igneous Cur",
"Igneous Elemental",
"Igneous Inspiration",
"Ill-Gotten Inheritance",
"Illusionist's Stratagem",
"Illustrious Historian",
"Ilysian Caryatid",
"Immersturm Raider",
"Immersturm Skullcairn",
"Immolation",
"Impale",
"Impassioned Orator",
"Impeccable Timing",
"Impending Doom",
"Imperial Aerosaur",
"Imperial Ceratops",
"Imperial Lancer",
"Imperial Outrider",
"Imperious Oligarch",
"Imperious Perfect",
"Implement of Combustion",
"Implement of Examination",
"Implement of Malice",
"Imposing Vantasaur",
"Impostor of the Sixth Pride",
"Improbable Alliance",
"Improvised Weaponry",
"In Bolas's Clutches",
"In Oketra's Name",
"Incendiary Oracle",
"Incorrigible Youths",
"Incremental Growth",
"Incubation // Incongruity",
"Indatha Crystal",
"Indomitable Will",
"Indulgent Aristocrat",
"Indulging Patrician",
"Inescapable Blaze",
"Inevitable End",
"Infectious Horror",
"Infernal Grasp",
"Infernal Pet",
"Infernal Scarring",
"Inferno Hellion",
"Infestation Expert",
"Infuriate",
"Infuse with Vitality",
"Inga Rune-Eyes",
"Ingenious Infiltrator",
"Ingenious Smith",
"Initiate's Companion",
"Inkling Summoning",
"Innocent Blood",
"Innocent Traveler",
"Inordinate Rage",
"Inquisition of Kozilek",
"Inquisitive Puppet",
"Insatiable Appetite",
"Insatiable Gorgers",
"Insatiable Hemophage",
"Insolent Neonate",
"Inspire Awe",
"Inspired Charge",
"Inspiring Bard",
"Inspiring Call",
"Inspiring Captain",
"Inspiring Cleric",
"Inspiring Unicorn",
"Inspiring Veteran",
"Intangible Virtue",
"Integrity // Intervention",
"Interplanar Beacon",
"Into the Night",
"Into the North",
"Into the Roil",
"Into the Story",
"Intrepid Outlander",
"Introduction to Annihilation",
"Introduction to Prophecy",
"Intrusive Packbeast",
"Invade the City",
"Invading Manticore",
"Invasion of the Giants",
"Inventor's Apprentice",
"Inventor's Goggles",
"Invert // Invent",
"Invigorated Rampage",
"Invigorating Surge",
"Invoke the Divine",
"Ipnu Rivulet",
"Iridescent Hornbeetle",
"Iroas's Blessing",
"Iron Bully",
"Iron Golem",
"Iron Verdict",
"Ironclad Krovod",
"Ironroot Warlord",
"Ironshell Beetle",
"Irontread Crusher",
"Irregular Cohort",
"Irresistible Prey",
"Irreverent Revelers",
"Island",
"Ivy Elemental",
"Ixalan's Binding",
"Ixalli's Diviner",
"Ixalli's Keeper",
"Izzet Guildgate",
"Izzet Locket",
"Jace's Projection",
"Jace's Sentinel",
"Jace's Triumph",
"Jack-o'-Lantern",
"Jade Bearer",
"Jade Guardian",
"Jadecraft Artisan",
"Jaded Sell-Sword",
"Jarl of the Forsaken",
"Jaspera Sentinel",
"Jaya, Venerated Firemage",
"Jaya's Greeting",
"Jeskai Elder",
"Jewel-Eyed Cobra",
"Jhoira's Familiar",
"Jiang Yanggu, Wildcrafter",
"Join Shields",
"Join the Dance",
"Joraga Visionary",
"Journey to Oblivion",
"Joust",
"Jousting Dummy",
"Jousting Lance",
"Jubilant Skybonder",
"Juggernaut",
"Jungle Creeper",
"Jungle Delver",
"Jungle Hollow",
"Jungleborn Pioneer",
"Junk Winder",
"Junktroller",
"Just the Wind",
"Justice Strike",
"Justiciar's Portal",
"Jwari Disruption",
"Kabira Outrider",
"Kabira Takedown",
"Kalain, Reclusive Painter",
"Kalastria Nightwatch",
"Karametra's Blessing",
"Kardur, Doomscourge",
"Kardur's Vicious Return",
"Karfell Harbinger",
"Karfell Kennel-Master",
"Kargan Dragonrider",
"Kargan Warleader",
"Karok Wrangler",
"Karplusan Hound",
"Kasmina, Enigmatic Mentor",
"Kasmina's Transmutation",
"Kaya, Bane of the Dead",
"Kaya's Ghostform",
"Kaya's Onslaught",
"Kazandu Nectarpot",
"Kazandu Stomper",
"Kazuul's Fury",
"Keen Glidemaster",
"Keen-Eared Sentry",
"Keensight Mentor",
"Keep Safe",
"Keeper of Fables",
"Kefnet's Monument",
"Keldon Overseer",
"Keldon Raider",
"Keldon Warcaller",
"Kelpie Guide",
"Kenrith's Transformation",
"Keral Keep Disciples",
"Kessig Flamebreather",
"Kessig Naturalist",
"Ketria Crystal",
"Khalni Ambush",
"Khalni Garden",
"Khenra Charioteer",
"Khenra Eternal",
"Khenra Scrapper",
"Kick in the Door",
"Killian, Ink Duelist",
"Kiln Fiend",
"Kindly Ancestor",
"Kindred Denial",
"Kinetic Augur",
"King Harald's Revenge",
"King of the Pride",
"Kinjalli's Caller",
"Kiora, Behemoth Beckoner",
"Kiora's Dambreaker",
"Kitchen Imp",
"Kitesail Cleric",
"Kitesail Corsair",
"Kitesail Freebooter",
"Klothys's Design",
"Knight of Grace",
"Knight of Malice",
"Knight of New Benalia",
"Knight of Sorrows",
"Knight of the Keep",
"Knight of the Last Breath",
"Knight of the Stampede",
"Knight of the Tusk",
"Knight's Pledge",
"Knightly Valor",
"Koll, the Forgemaster",
"Koma's Faithful",
"Kor Blademaster",
"Kor Celebrant",
"Kor Skyfisher",
"Kraul Foragers",
"Kraul Harpooner",
"Kraul Raider",
"Kraul Stinger",
"Kraul Swarm",
"Krenko's Command",
"Kronch Wrangler",
"Krosan Druid",
"Krosan Grip",
"Krosan Tusker",
"Krovikan Scoundrel",
"Krydle of Baldur's Gate",
"Kujar Seedsculptor",
"Kuldotha Flamefiend",
"Kumena's Speaker",
"Kwende, Pride of Femeref",
"Labyrinth Guardian",
"Lacerate Flesh",
"Lagonna-Band Storyteller",
"Laid to Rest",
"Lambholt Harrier",
"Lambholt Raconteur",
"Lampad of Death's Vigil",
"Lancer Sliver",
"Lantern Bearer",
"Lantern of the Lost",
"Larder Zombie",
"Lash of Malice",
"Lash of Thorns",
"Last Gasp",
"Late to Dinner",
"Lathnu Sailback",
"Launch Party",
"Lava Axe",
"Lava Coil",
"Lava Serpent",
"Lavabelly Sliver",
"Lavakin Brawler",
"Law-Rune Enforcer",
"Lawless Broker",
"Lawmage's Binding",
"Lay Claim",
"Lazotep Behemoth",
"Lazotep Chancellor",
"Lazotep Plating",
"Lazotep Reaver",
"Lead the Stampede",
"Leaf Gilder",
"Leafkin Avenger",
"Leafkin Druid",
"League Guildmage",
"Leapfrog",
"Leather Armor",
"Leave in the Dust",
"Ledev Champion",
"Ledev Guardian",
"Leech Fanatic",
"Leeching Sliver",
"Legion Conquistador",
"Legion Guildmage",
"Legion Lieutenant",
"Legion Vanguard",
"Legion's Judgment",
"Leonin of the Lost Pride",
"Leonin Sanctifier",
"Leonin Vanguard",
"Lethal Sting",
"Letter of Acceptance",
"Leyline Invocation",
"Leyline Prowler",
"Library Larcenist",
"Lich's Caress",
"Life Goes On",
"Lifecraft Cavalry",
"Lifecrafter's Gift",
"Light of Hope",
"Light of Promise",
"Light Up the Stage",
"Lightfoot Rogue",
"Lightning Axe",
"Lightning Diadem",
"Lightning Elemental",
"Lightning Helix",
"Lightning Mare",
"Lightning Shrieker",
"Lightning Spear",
"Lightning Stormkin",
"Lightning Strike",
"Lightning Visionary",
"Lightning Wolf",
"Lightning-Core Excavator",
"Lightning-Rig Crew",
"Lightwalker",
"Liliana's Defeat",
"Liliana's Devotee",
"Liliana's Elite",
"Liliana's Scrounger",
"Liliana's Steward",
"Liliana's Triumph",
"Lingering Phantom",
"Lithoform Blight",
"Littjara Glade-Warden",
"Littjara Kinseekers",
"Littjara Mirrorlake",
"Live Fast",
"Living Lightning",
"Living Tempest",
"Llanowar Elves",
"Llanowar Envoy",
"Llanowar Scout",
"Llanowar Tribe",
"Llanowar Visionary",
"Loaming Shaman",
"Loathsome Chimera",
"Loathsome Troll",
"Loch Dragon",
"Locked in the Cemetery",
"Locthwain Gargoyle",
"Locthwain Paladin",
"Lofty Denial",
"Lonely Sandbar",
"Lonesome Unicorn",
"Long Road Home",
"Longtusk Cub",
"Longtusk Stalker",
"Lookout's Dispersal",
"Looming Altisaur",
"Lord of the Accursed",
"Lore Drakkis",
"Lorehold Apprentice",
"Lorehold Campus",
"Lorehold Excavation",
"Lorehold Pledgemage",
"Lorescale Coatl",
"Lost Legion",
"Lotleth Giant",
"Loxodon Line Breaker",
"Loxodon Restorer",
"Loxodon Sergeant",
"Loyal Gryff",
"Loyal Pegasus",
"Lucky Clover",
"Lullmage's Domination",
"Lullmage's Familiar",
"Lumbering Lightshield",
"Luminous Bonds",
"Lunar Frenzy",
"Lunar Rejection",
"Lunarch Veteran",
"Lurking Chupacabra",
"Lurking Deadeye",
"Lurking Roper",
"Lys Alana Huntmaster",
"Macabre Mockery",
"Macabre Waltz",
"Mad Prophet",
"Mad Ratter",
"Maelstrom Muse",
"Mage Duel",
"Mage Hunter",
"Mage Hunters' Onslaught",
"Magic Missile",
"Magma Jet",
"Magma Pummeler",
"Magma Spray",
"Magmaroth",
"Maja, Bretagard Protector",
"Majestic Auricorn",
"Majestic Heliopterus",
"Make a Stand",
"Make Obsolete",
"Make Your Mark",
"Makeshift Battalion",
"Makeshift Munitions",
"Makindi Ox",
"Makindi Stampede",
"Malakir Blood-Priest",
"Malakir Cullblade",
"Malakir Familiar",
"Malakir Rebirth",
"Malefic Scythe",
"Malevolent Noble",
"Malfunction",
"Mammoth Growth",
"Mammoth Spider",
"Man-o'-War",
"Mana Geode",
"Mana Tithe",
"Manalith",
"Manaweft Sliver",
"Maned Serval",
"Manglehorn",
"Maniacal Rage",
"Manic Scribe",
"Manifold Key",
"Manor Guardian",
"Manticore",
"Mantle of Tides",
"Maraleaf Pixie",
"Maraleaf Rider",
"Marauder's Axe",
"Marauding Blight-Priest",
"Marauding Boneslasher",
"Marauding Looter",
"March of the Drowned",
"Mark of the Vampire",
"Markov Crusader",
"Markov Purifier",
"Markov Retribution",
"Markov Waltzer",
"Martyr for the Cause",
"Martyr of Dusk",
"Mascot Interception",
"Mask of Immolation",
"Masked Blackguard",
"Masked Vandal",
"Massive Might",
"Master Skald",
"Master Splicer",
"Master Symmetrist",
"Maulfist Revolutionary",
"Maulfist Squad",
"Mausoleum Harpy",
"Maverick Thopterist",
"Maximize Altitude",
"Maximize Velocity",
"Mayhem Devil",
"Meandering River",
"Medomai's Prophecy",
"Memorial to Folly",
"Memorial to Genius",
"Memorial to Glory",
"Memorial to Unity",
"Memorial to War",
"Memory Drain",
"Memory Leak",
"Memory Theft",
"Mentor of Evos Isle",
"Mentor's Guidance",
"Mephitic Vapors",
"Merchant of the Vale",
"Merciless Javelineer",
"Mercurial Transformation",
"Merfolk Branchwalker",
"Merfolk Falconer",
"Merfolk Looter",
"Merfolk Mistbinder",
"Merfolk Secretkeeper",
"Merfolk Skydiver",
"Merfolk Trickster",
"Merfolk Windrobber",
"Merrow Reejerey",
"Mesa Lynx",
"Mesa Unicorn",
"Metallic Rebuke",
"Meteor Golem",
"Meteorite",
"Metropolis Sprite",
"Miasmic Mummy",
"Might of Murasa",
"Might of the Masses",
"Might of the Old Ways",
"Mighty Leap",
"Migration Path",
"Migratory Greathorn",
"Militia Bugler",
"Militia Rallier",
"Millstone",
"Mimic",
"Mind Carver",
"Mind Drain",
"Mind Rake",
"Mind Rot",
"Mind Stone",
"Mindleech Ghoul",
"Mindwrack Harpy",
"Minimus Containment",
"Minion's Return",
"Minister of Inquiries",
"Ministrant of Obligation",
"Minotaur Skullcleaver",
"Minotaur Sureshot",
"Mire Triton",
"Mire's Grasp",
"Mirrodin's Core",
"Mirror Image",
"Mirror Shield",
"Miscast",
"Mischievous Catgeist",
"Mischievous Chimera",
"Mist-Cloaked Herald",
"Mistford River Turtle",
"Mistral Singer",
"Mists of Littjara",
"Mistwalker",
"Moat Piranhas",
"Mob",
"Mobile Garrison",
"Mogis's Favor",
"Molderhulk",
"Moldering Karok",
"Moldervine Reclamation",
"Moldgraf Millipede",
"Molten Blast",
"Molten Ravager",
"Moment of Craving",
"Moment of Heroism",
"Moment of Triumph",
"Momentary Blink",
"Momentum Rumbler",
"Monk of the Open Hand",
"Monoskelion",
"Monstrous Onslaught",
"Monstrous Step",
"Moodmark Painter",
"Moon-Blessed Cleric",
"Moonblade Shinobi",
"Moonlit Scavengers",
"Moonrager's Slash",
"Moonsilver Key",
"Moorland Inquisitor",
"Morbid Opportunist",
"Mordenkainen's Polymorph",
"Moritte of the Frost",
"Morkrut Behemoth",
"Mortality Spear",
"Mortify",
"Moss Viper",
"Moss-Pit Skeleton",
"Mosscoat Goriak",
"Mother Bear",
"Mountain",
"Mounted Dreadknight",
"Mourning Patrol",
"Mowu, Loyal Companion",
"Mugging",
"Mulch",
"Mulldrifter",
"Munitions Expert",
"Murasa Behemoth",
"Murasa Brute",
"Murasa Rootgrazer",
"Murasa Sproutling",
"Murder",
"Murmuring Mystic",
"Murmuring Phantasm",
"Muse Drake",
"Mutiny",
"Mutual Destruction",
"Myr Enforcer",
"Myr Scrapling",
"Myr Sire",
"Mysterious Egg",
"Mysterious Pathlighter",
"Mysterious Tome",
"Mystic Repeal",
"Mystic Sanctuary",
"Mystic Skull",
"Mystic Skyfish",
"Mystic Subdual",
"Mystical Dispute",
"Naga Eternal",
"Naga Oracle",
"Naga Vitalist",
"Nahiri, Storm of Stone",
"Nahiri's Binding",
"Nahiri's Stoneblades",
"Naiad of Hidden Coves",
"Nantuko Cultivator",
"Narcolepsy",
"Narcomoeba",
"Narfi, Betrayer King",
"Narnam Cobra",
"Narnam Renegade",
"Narset, Parter of Veils",
"Natural End",
"Naturalize",
"Nature's Embrace",
"Nature's Spiral",
"Nature's Way",
"Navigator's Compass",
"Navigator's Ruin",
"Nebelgast Beguiler",
"Nebelgast Herald",
"Nebelgast Intruder",
"Necromancer's Familiar",
"Necropanther",
"Necrosynthesis",
"Necrotic Fumes",
"Necrotic Wound",
"Needlethorn Drake",
"Needletooth Raptor",
"Nef-Crop Entangler",
"Negate",
"Neoform",
"Neonate's Rush",
"Nessian Hornbeetle",
"Nessian Wanderer",
"Nest of Scarabs",
"Nest Robber",
"Nested Shambler",
"Netcaster Spider",
"Neutralize",
"Never Happened",
"Neverwinter Dryad",
"New Horizons",
"Nexus Wardens",
"Nezumi Cutthroat",
"Night Market Aeronaut",
"Night Market Lookout",
"Nightmare's Thirst",
"Nightshade Stinger",
"Nightsquad Commando",
"Nightveil Predator",
"Nightveil Sprite",
"Niko Defies Destiny",
"Nimana Skitter-Sneak",
"Nimana Skydancer",
"Nimble Birdsticker",
"Nimble Innovator",
"Nimble Pilferer",
"Nimble-Blade Khenra",
"Nimbus Swimmer",
"Ninja of the Deep Hours",
"Nissa's Triumph",
"Nissa's Zendikon",
"No Escape",
"No Way Out",
"Nocturnal Feeder",
"Notion Rain",
"Novice Dissector",
"Novice Knight",
"Novice Occultist",
"Noxious Grasp",
"Noxious Groodion",
"Nurturing Presence",
"Nylea's Forerunner",
"Nylea's Huntmaster",
"Nyx Herald",
"Nyx-Fleece Ram",
"Nyxborn Brute",
"Nyxborn Colossus",
"Nyxborn Courser",
"Nyxborn Marauder",
"Nyxborn Seaguard",
"Oakenform",
"Oakhame Adversary",
"Oakhame Ranger",
"Oakshade Stalker",
"Oashra Cultivator",
"Oasis Ritualist",
"Oathsworn Vampire",
"Ob Nixilis, the Hate-Twisted",
"Ob Nixilis's Cruelty",
"Obelisk Spider",
"Oblivion's Hunger",
"Obsessive Astronomer",
"Obsessive Stitcher",
"Ochran Assassin",
"Octoprophet",
"Odric's Outrider",
"Of One Mind",
"Oggyar Battle-Seer",
"Ogre Errant",
"Ogre Siegebreaker",
"Ojutai's Summons",
"Oketra's Attendant",
"Oketra's Avenger",
"Oketra's Monument",
"Okiba-Gang Shinobi",
"Oko's Accomplices",
"Olivia's Midnight Ambush",
"Ollenbock Escort",
"Omen of the Dead",
"Omen of the Forge",
"Omen of the Hunt",
"Omen of the Sea",
"Omen of the Sun",
"Omenspeaker",
"Ominous Roost",
"Ominous Seas",
"Ominous Sphinx",
"On Serra's Wings",
"Onakke Ogre",
"Once and Future",
"One with the Stars",
"One With the Wind",
"Oneirophage",
"Onward /// Victory",
"Oona's Blackguard",
"Open Fire",
"Open the Gates",
"Open the Omenpaths",
"Opt",
"Orazca Frillback",
"Orazca Raptor",
"Orazca Relic",
"Orcish Vandal",
"Order of Midnight",
"Ore-Scale Guardian",
"Oread of Mountain's Blaze",
"Oreskos Swiftclaw",
"Organ Hoarder",
"Ornamental Courage",
"Ornery Dilophosaur",
"Ornery Goblin",
"Ornery Kudu",
"Ornithopter",
"Ornithopter of Paradise",
"Orzhov Enforcer",
"Orzhov Guildgate",
"Orzhov Locket",
"Orzhov Racketeers",
"Otepec Huntmaster",
"Otherworldly Gaze",
"Outflank",
"Outland Boar",
"Outland Liberator",
"Outmuscle",
"Outnumber",
"Ovalchase Dragster",
"Overcome",
"Overgrown Arch",
"Overgrown Armasaur",
"Overgrown Battlement",
"Overgrowth Elemental",
"Overwhelmed Apprentice",
"Overwhelmed Archivist",
"Owlbear",
"Owlin Shieldmage",
"Pacification Array",
"Pacifism",
"Pack Mastiff",
"Pack's Betrayal",
"Pack's Favor",
"Packsong Pup",
"Paired Tactician",
"Paladin of the Bloodstained",
"Paladin's Shield",
"Palladium Myr",
"Panicked Bystander",
"Paradise Druid",
"Parasitic Grasp",
"Parasitic Implant",
"Parcel Myr",
"Parcelbeast",
"Pardic Wanderer",
"Parhelion Patrol",
"Parish-Blade Trainee",
"Passwall Adept",
"Patagia Tiger",
"Path to the Festival",
"Path to the World Tree",
"Pathmaker Initiate",
"Patron of the Valiant",
"Pattern Matcher",
"Pause for Reflection",
"Peel from Reality",
"Peema Aether-Seer",
"Peema Outrider",
"Pegasus Courser",
"Pelakka Predation",
"Pelakka Wurm",
"Pendulum of Patterns",
"Penumbra Bobcat",
"Perilous Myr",
"Perilous Voyage",
"Perimeter Sergeant",
"Persistent Petitioners",
"Persistent Specimen",
"Pest Summoning",
"Pestilent Haze",
"Pestilent Wolf",
"Phalanx Tactics",
"Phantasmal Form",
"Phantom Carriage",
"Phantom Ninja",
"Phantom Warrior",
"Pharika's Libation",
"Pharika's Spawn",
"Phase Dolphin",
"Pheres-Band Brawler",
"Phyrexian Broodlings",
"Phyrexian Debaser",
"Phyrexian Gargantua",
"Phyrexian Rager",
"Phyrexian Reclamation",
"Pierce the Sky",
"Piercing Light",
"Pigment Storm",
"Pilfering Hawk",
"Pilfering Imp",
"Pilgrim of the Ages",
"Pillar of Flame",
"Pillar of Origins",
"Pillardrop Rescuer",
"Pillardrop Warden",
"Pious Interdiction",
"Pious Wayfarer",
"Pirate's Cutlass",
"Pirate's Pillage",
"Pirate's Prize",
"Piston-Fist Cyclops",
"Pitchburn Devils",
"Pitiless Gorgon",
"Pitiless Plunderer",
"Pitiless Pontiff",
"Pitiless Vizier",
"Pixie Guide",
"Plague Mare",
"Plague Wight",
"Plaguecrafter",
"Plaguecrafter's Familiar",
"Plagued Rusalka",
"Plains",
"Planar Ally",
"Plate Armor",
"Play with Fire",
"Pledge of Unity",
"Plumb the Forbidden",
"Plummet",
"Plundering Barbarian",
"Pointed Discussion",
"Poison the Cup",
"Poison-Tip Archer",
"Pollenbright Druid",
"Pollywog Symbiote",
"Pondering Mage",
"Pop Quiz",
"Porcuparrot",
"Port of Karfell",
"Portable Hole",
"Portal of Sanctuary",
"Portcullis Vine",
"Portent of Betrayal",
"Potion of Healing",
"Pounce",
"Pouncing Cheetah",
"Pouncing Lynx",
"Pouncing Shoreshark",
"Power of Persuasion",
"Power Word Kill",
"Powerstone Shard",
"Practical Research",
"Practiced Tactics",
"Prakhata Pillar-Bug",
"Precipitous Drop",
"Precise Strike",
"Precision Bolt",
"Predatory Sliver",
"Predatory Wurm",
"Prescient Chimera",
"Presence of Gond",
"Pressure Point",
"Prey Upon",
"Prey's Vengeance",
"Price of Betrayal",
"Price of Fame",
"Price of Loyalty",
"Prickly Marmoset",
"Pride of Conquerors",
"Pridemalkin",
"Priest of Ancient Lore",
"Priest of the Haunted Edge",
"Primal Empathy",
"Primordial Wurm",
"Prismari Apprentice",
"Prismari Campus",
"Prismari Pledgemage",
"Prismite",
"Prison Realm",
"Prized Griffin",
"Prized Unicorn",
"Professor of Symbology",
"Professor of Zoomancy",
"Professor's Warning",
"Promising Duskmage",
"Propeller Pioneer",
"Prophet of the Peak",
"Prophetic Prism",
"Prophetic Titan",
"Prosperous Innkeeper",
"Prosperous Pirates",
"Protection of the Hekma",
"Proud Wildbonder",
"Provoke the Trolls",
"Prowling Caracal",
"Prowling Felidar",
"Prying Blade",
"Prying Eyes",
"Psychic Corrosion",
"Psychic Symbiont",
"Pteramander",
"Pterodon Knight",
"Pulse of Murasa",
"Puncturing Blow",
"Purifying Dragon",
"Purple Worm",
"Pursue Glory",
"Putrefy",
"Putrid Goblin",
"Pyre Spawn",
"Pyroceratops",
"Pyroclastic Elemental",
"Pyroclastic Hellion",
"Pyromantic Pilgrim",
"Quandrix Apprentice",
"Quandrix Campus",
"Quandrix Cultivator",
"Quandrix Pledgemage",
"Quarry Hauler",
"Queen of Ice",
"Queen's Agent",
"Queen's Bay Soldier",
"Queen's Commission",
"Quench",
"Quicksmith Genius",
"Quintorius, Field Historian",
"Quirion Dryad",
"Rabid Bite",
"Radiant Fountain",
"Radiant Grace",
"Radiant's Judgment",
"Radiating Lightning",
"Radical Idea",
"Raff Capashen, Ship's Mage",
"Rafter Demon",
"Rage Forger",
"Rage-Scarred Berserker",
"Ragefire",
"Ragged Recluse",
"Raging Goblin",
"Raging Kronch",
"Raging Redcap",
"Raging Regisaur",
"Raging Swordtooth",
"Raid Bombardment",
"Raiders' Karve",
"Raiders' Wake",
"Rain of Revelation",
"Raise Dead",
"Raise the Alarm",
"Raise the Draugr",
"Rakdos Firewheeler",
"Rakdos Guildgate",
"Rakdos Headliner",
"Rakdos Locket",
"Rakdos Roustabout",
"Rakdos Trumpeter",
"Raking Claws",
"Ral's Outburst",
"Ral's Staticaster",
"Rally for the Throne",
"Rally Maneuver",
"Rally of Wings",
"Rally to Battle",
"Rallying Roar",
"Ram Through",
"Rambunctious Mutt",
"Rampage of the Valkyries",
"Rampaging Cyclops",
"Rampaging Monument",
"Rampaging Rendhorn",
"Rampart Smasher",
"Ramunap Ruins",
"Ranger's Guile",
"Ranger's Hawk",
"Ranger's Longbow",
"Ranging Raptors",
"Ransack the Lab",
"Rapacious Dragon",
"Raptor Companion",
"Raptor Hatchling",
"Rat Colony",
"Raugrin Crystal",
"Ravager's Mace",
"Raven Wings",
"Ravenform",
"Ravenous Bloodseeker",
"Ravenous Chupacabra",
"Ravenous Daggertooth",
"Ravenous Harpy",
"Ravenous Intruder",
"Ravenous Lindwurm",
"Ravenous Squirrel",
"Raving Visionary",
"Ray of Enfeeblement",
"Ray of Frost",
"Ray of Revelation",
"Raze the Effigy",
"Read the Tides",
"Reaper of Night",
"Reaper's Talisman",
"Reassembling Skeleton",
"Reave Soul",
"Reaver Ambush",
"Recalibrate",
"Reckless Air Strike",
"Reckless Amplimancer",
"Reckless Charge",
"Reckless Fireweaver",
"Reckless Impulse",
"Reckless Racer",
"Reckless Rage",
"Reckless Ringleader",
"Reckless Scholar",
"Reckless Wurm",
"Reclaim the Wastes",
"Reclamation Sage",
"Reclusive Taxidermist",
"Recollect",
"Reconnaissance Mission",
"Reconstruct History",
"Recover",
"Red Dragon",
"Redcap Melee",
"Redcap Raiders",
"Reduce /// Rubble",
"Reduce to Ashes",
"Reduce to Memory",
"Reflective Golem",
"Refurbish",
"Regal Bloodlord",
"Regal Leosaur",
"Regenesis",
"Regrowth",
"Reject",
"Release the Dogs",
"Relentless Advance",
"Relentless Pursuit",
"Relentless Raptor",
"Relic Amulet",
"Relic Axe",
"Relic Golem",
"Relic of Progenitus",
"Relic Runner",
"Relic Sloth",
"Relic Vial",
"Reliquary Tower",
"Renata, Called to the Hunt",
"Rending Flame",
"Renegade Map",
"Renegade Rallier",
"Renegade Reaper",
"Renegade Tactics",
"Renegade Wheelsmith",
"Renewed Faith",
"Renowned Weaponsmith",
"Replicating Ring",
"Repository Skaab",
"Reprobation",
"Reptilian Reflection",
"Rescue",
"Rescuer Sphinx",
"Resculpt",
"Reservoir Walker",
"Resistance Squad",
"Resolute Rider",
"Resolute Strike",
"Resolute Watchdog",
"Resplendent Griffin",
"Restless Bloodseeker",
"Restoration Gearsmith",
"Restoration Specialist",
"Retributive Wand",
"Retrieve",
"Return to Nature",
"Return Upon the Tide",
"Returned Pastcaller",
"Revenge of Ravens",
"Revenge of the Drowned",
"Reverent Hoplite",
"Reverse Engineer",
"Revitalize",
"Revoke Existence",
"Revoke Privileges",
"Revolutionary Rebuff",
"Revolutionist",
"Rewind",
"Rhizome Lurcher",
"Rhonas's Monument",
"Rhonas's Stalwart",
"Rhox Oracle",
"Rhythm of the Wild",
"Riddle of Lightning",
"Riddleform",
"Ridgescale Tusker",
"Rigging Runner",
"Righteous Blow",
"Righteousness",
"Rile",
"Rimeshield Frost Giant",
"Rimewall Protector",
"Rimewood Falls",
"Rimrock Knight",
"Rip Apart",
"Riparian Tiger",
"Ripscale Predator",
"Riptide Turtle",
"Rise Again",
"Rise from the Grave",
"Rise of Extus",
"Rise of the Ants",
"Rise to Glory",
"Risen Reef",
"Risen Riptide",
"Rishadan Airship",
"Rising Populace",
"Rite of Oblivion",
"Ritual Guardian",
"Ritual of Hope",
"Ritual of Rejuvenation",
"River Darter",
"River Heralds' Boon",
"River Hoopoe",
"River Sneak",
"River's Favor",
"Riverwise Augur",
"Roaming Ghostlight",
"Roar of the Wurm",
"Roc Charger",
"Roc Egg",
"Rockslide Sorcerer",
"Rogue Refiner",
"Rogue's Gloves",
"Roil Eruption",
"Roiling Regrowth",
"Rona, Disciple of Gix",
"Ronom Unicorn",
"Rookie Mistake",
"Roost of Drakes",
"Root Snare",
"Rootcoil Creeper",
"Rootha, Mercurial Artist",
"Rooting Moloch",
"Rootless Yew",
"Roots of Wisdom",
"Rosemane Centaur",
"Rosethorn Acolyte",
"Rosethorn Halberd",
"Rot-Tide Gargantua",
"Rotten Reunion",
"Rotwidow Pack",
"Rousing Read",
"Roving Keep",
"Rowan's Battleguard",
"Rubble Reading",
"Rubble Slinger",
"Rubblebelt Boar",
"Rubblebelt Recluse",
"Rubblebelt Rioters",
"Rubblebelt Runner",
"Rugged Highlands",
"Ruin Crab",
"Ruin Rat",
"Ruination Rioter",
"Ruinous Gremlin",
"Rule of Law",
"Rumbling Baloth",
"Rumbling Rockslide",
"Rumbling Ruin",
"Rumbling Sentry",
"Rummaging Goblin",
"Run Afoul",
"Run Aground",
"Run Amok",
"Run Ashore",
"Run Away Together",
"Rune of Flight",
"Rune of Might",
"Rune of Mortality",
"Rune of Speed",
"Rune of Sustenance",
"Runebound Wolf",
"Runeclaw Bear",
"Runed Crown",
"Runed Servitor",
"Rupture Spire",
"Rural Recruit",
"Rush of Vitality",
"Rust Monster",
"Rustwing Falcon",
"Ruthless Knave",
"Ruthless Sniper",
"Sabertooth Mauler",
"Sacred Cat",
"Sacred Fire",
"Sadistic Skymarcher",
"Sage of Lat-Nam",
"Sage of Mysteries",
"Sage of Shaila's Claim",
"Sage of the Falls",
"Sage's Row Denizen",
"Sage's Row Savant",
"Sagittars' Volley",
"Saheeli, Sublime Artificer",
"Saheeli's Silverwing",
"Sailor of Means",
"Salivating Gremlins",
"Salvager of Ruin",
"Salvager of Secrets",
"Samut, Tyrant Smasher",
"Samut's Sprint",
"Sanctify",
"Sanctuary Cat",
"Sanctuary Lockdown",
"Sanctuary Raptor",
"Sanctuary Smasher",
"Sanctum of Calm Waters",
"Sanctum of Fruitful Harvest",
"Sanctum of Shattered Heights",
"Sanctum of Stone Fangs",
"Sanctum of Tranquil Light",
"Sanctum Spirit",
"Sand Strangler",
"Sandsteppe Outcast",
"Sanguine Glorifier",
"Sanguine Indulgence",
"Sanguine Statuette",
"Sanitarium Skeleton",
"Saproling Migration",
"Sarkhan's Catharsis",
"Sarkhan's Rage",
"Sarkhan's Scorn",
"Sarkhan's Whelp",
"Sarulf's Packmate",
"Saruli Caretaker",
"Satyr Enchanter",
"Satyr's Cunning",
"Sauroform Hybrid",
"Savage Gorger",
"Savage Smash",
"Savage Stomp",
"Savage Swipe",
"Savai Crystal",
"Savai Sabertooth",
"Savai Thundermane",
"Savannah Sage",
"Savvy Hunter",
"Saw It Coming",
"Sawblade Slinger",
"Scalding Cauldron",
"Scale the Heights",
"Scale Up",
"Scaled Herbalist",
"Scampering Scorcher",
"Scarab Feast",
"Scathe Zombies",
"Scattered Thoughts",
"Scavenged Blade",
"Scavenging Harpy",
"Scholar of Stars",
"Scholar of the Ages",
"Scion of Shiv",
"Scion of Stygia",
"Scion of the Swarm",
"Scorch Rider",
"Scorch Spitter",
"Scorching Dragonfire",
"Scorchmark",
"Scorn Effigy",
"Scour All Possibilities",
"Scour the Desert",
"Scour the Laboratory",
"Scoured Barrens",
"Scrabbling Claws",
"Scrapper Champion",
"Screaming Shield",
"Screaming Swarm",
"Scroll of Avacyn",
"Sculptor of Winter",
"Scurrid Colony",
"Scurry Oak",
"Scuttlegator",
"Scuttlemutt",
"Scuttletide",
"Scuttling Sliver",
"Sea Gate Banneret",
"Sea Gate Colossus",
"Sea Gate Oracle",
"Sea God's Scorn",
"Sea Legs",
"Seafloor Stalker",
"Seal Away",
"Search Party Captain",
"Searing Barrage",
"Season of Growth",
"Seasoned Hallowblade",
"Secluded Steppe",
"Secret Door",
"Secret Rendezvous",
"Secrets of the Golden City",
"Secrets of the Key",
"Secure the Scene",
"Sedge Scorpion",
"See Red",
"Seeker of Insight",
"Seekers' Squire",
"Seer of the Last Tomorrow",
"Segovian Angel",
"Seismic Elemental",
"Seismic Shift",
"Seize the Spoils",
"Seize the Storm",
"Sejiri Shelter",
"Select for Inspection",
"Selective Snare",
"Selesnya Guildgate",
"Selesnya Locket",
"Self-Assembler",
"Selfless Cathar",
"Selfless Savior",
"Selhoff Entomber",
"Selhoff Occultist",
"Senate Courier",
"Senate Griffin",
"Senate Guildmage",
"Sengir Vampire",
"Sentinel of the Pearl Trident",
"Sentinel Sliver",
"Sentinel Spider",
"Sentinel Totem",
"Sentinel's Eyes",
"Sentinel's Mark",
"Sepulcher Ghoul",
"Seraph of Dawn",
"Serendib Efreet",
"Sergeant-at-Arms",
"Serpentine Ambush",
"Serpentine Curve",
"Serra Angel",
"Serra Disciple",
"Serrated Scorpion",
"Servant of the Conduit",
"Servant of the Scale",
"Servo Exhibition",
"Servo Schematic",
"Setessan Petitioner",
"Setessan Skirmisher",
"Setessan Training",
"Settle the Score",
"Settle the Wilds",
"Seven Dwarves",
"Severed Strands",
"Shackles of Treachery",
"Shadewing Laureate",
"Shadow Stinger",
"Shadowbeast Sighting",
"Shadowstorm Vizier",
"Shady Traveler",
"Shake the Foundations",
"Shambleshark",
"Shambling Ghast",
"Shambling Goblin",
"Shambling Suit",
"Shanna, Sisay's Legacy",
"Shaper Apprentice",
"Shapers of Nature",
"Sharktocrab",
"Shatter",
"Shatterskull Minotaur",
"Shatterstorm",
"Shed Weakness",
"Shefet Dunes",
"Shefet Monitor",
"Shell Shield",
"Shelter",
"Sheltering Boughs",
"Sheltering Light",
"Shepherd of Heroes",
"Shepherd of the Cosmos",
"Shepherd of the Flock",
"Shessra, Death's Whisper",
"Shield Mare",
"Shield of the Realm",
"Shielded Aether Thief",
"Shimmer of Possibility",
"Shimmerdrift Vale",
"Shimmerscale Drake",
"Shimmerwing Chimera",
"Shinechaser",
"Shining Aerosaur",
"Shining Armor",
"Shipwreck Dowser",
"Shipwreck Looter",
"Shipwreck Moray",
"Shipwreck Sifters",
"Shiv's Embrace",
"Shivan Fire",
"Shoal Kraken",
"Shock",
"Shocking Grasp",
"Shore Keeper",
"Shoreline Scout",
"Short Sword",
"Shortcut Seeker",
"Show of Confidence",
"Show of Valor",
"Shredded Sails",
"Shrewd Negotiation",
"Shriekdiver",
"Shrine Keeper",
"Sidewinder Naga",
"Siege Mastodon",
"Siege Modification",
"Siege Striker",
"Siege Wurm",
"Siege Zombie",
"Siegebreaker Giant",
"Sift",
"Sifter Wurm",
"Sigarda's Imprisonment",
"Sigardian Paladin",
"Sigiled Contender",
"Sigiled Starfish",
"Sign in Blood",
"Signpost Scarecrow",
"Silent Dart",
"Silent Departure",
"Silhana Wayfinder",
"Silundi Vision",
"Silver Bolt",
"Silver Raven",
"Silverback Shaman",
"Silverbeak Griffin",
"Silverflame Ritual",
"Silverflame Squire",
"Silvergill Adept",
"Silverquill Apprentice",
"Silverquill Campus",
"Silverquill Pledgemage",
"Silversmote Ghoul",
"Simic Guildgate",
"Simic Locket",
"Sinister Sabotage",
"Sinister Starfish",
"Siona, Captain of the Pyleas",
"Siren Lookout",
"Siren Reaver",
"Siren Stormtamer",
"Siren's Ruse",
"Sixth Sense",
"Sizzling Barrage",
"Skaab Wrangler",
"Skatewing Spy",
"Skeleton Archer",
"Skemfar Elderhall",
"Skemfar Shadowsage",
"Skewer the Critics",
"Skilled Animator",
"Skirk Prospector",
"Skitter Eel",
"Skittering Heartstopper",
"Skittering Surveyor",
"Skizzik",
"Skola Grovedancer",
"Skophos Maze-Warden",
"Skophos Reaver",
"Skophos Warleader",
"Skulduggery",
"Skulking Killer",
"Skull Prophet",
"Skull Raid",
"Skull Skaab",
"Skullknocker Ogre",
"Skullport Merchant",
"Skullsnatcher",
"Sky Skiff",
"Sky Terror",
"Sky Tether",
"Sky Theater Strix",
"Skyblade of the Legion",
"Skyblade's Boon",
"Skyclave Cleric",
"Skyclave Geopede",
"Skyclave Pick-Axe",
"Skyclave Plunder",
"Skyclave Sentinel",
"Skyclave Shadowcat",
"Skyclave Squid",
"Skyknight Legionnaire",
"Skyknight Vanguard",
"Skyline Scout",
"Skymarch Bloodletter",
"Skymarcher Aspirant",
"Skyrider Patrol",
"Skyscanner",
"Skyship Plunderer",
"Skyshroud Ambush",
"Skyshroud Lookout",
"Skywarp Skaab",
"Skyway Sniper",
"Skywhaler's Shot",
"Slag Strider",
"Slash of Talons",
"Slate Street Ruffian",
"Slaughter the Strong",
"Slaughter-Priest of Mogis",
"Slaying Fire",
"Sleek Schooner",
"Sleep",
"Sleep of the Dead",
"Sleep Paralysis",
"Sleeper Dart",
"Slice in Twain",
"Slimebind",
"Slimefoot, the Stowaway",
"Sling-Gang Lieutenant",
"Slinn Voda, the Rising Deep",
"Slippery Scoundrel",
"Slither Blade",
"Sly Requisitioner",
"Smashing Success",
"Smell Fear",
"Smelt",
"Smelt-Ward Ignus",
"Smelt-Ward Minotaur",
"Smite the Monstrous",
"Smitten Swordmaster",
"Snakeskin Veil",
"Snapping Drake",
"Snapping Sailback",
"Snare Tactician",
"Snarespinner",
"Snarling Wolf",
"Sneaking Guide",
"Snow Day",
"Snow-Covered Forest",
"Snow-Covered Island",
"Snow-Covered Mountain",
"Snow-Covered Plains",
"Snow-Covered Swamp",
"Snowfield Sinkhole",
"Snubhorn Sentry",
"So Shiny",
"So Tiny",
"Soaring Thought-Thief",
"Solid Footing",
"Solitary Camel",
"Solve the Equation",
"Somberwald Stag",
"Song of Freyalise",
"Song-Mad Treachery",
"Sonic Assault",
"Sonorous Howlbonder",
"Soothsayer Adept",
"Sorcerer of the Fang",
"Sorcerer's Broom",
"Sorcerer's Wand",
"Sorin's Thirst",
"Soul of Migration",
"Soul of the Rapids",
"Soul Salvage",
"Soul Sear",
"Soul Warden",
"Soul-Guide Gryff",
"Soul-Guide Lantern",
"Soulcipher Board",
"Soulherder",
"Soulknife Spy",
"Soulmender",
"Soulreaper of Mogis",
"Soulstealer Axe",
"Soulstinger",
"Sovereign's Bite",
"Spare Dagger",
"Spare Supplies",
"Spark Harvest",
"Spark Reaper",
"Sparktongue Dragon",
"Sparring Construct",
"Spear Spewer",
"Specimen Collector",
"Spectacle Mage",
"Specter of the Fens",
"Specter's Shriek",
"Spectral Sailor",
"Spectral Steel",
"Speedway Fanatic",
"Spell Pierce",
"Spell Satchel",
"Spelleater Wolverine",
"Spellgorger Weird",
"Spellkeeper Weird",
"Spellrune Painter",
"Spellweaver Eternal",
"Sphinx of New Prahv",
"Sphinx of the Guildpact",
"Sphinx's Insight",
"Spider Spawning",
"Spike-Tailed Ceratops",
"Spiked Pit Trap",
"Spiked Ripsaw",
"Spikefield Hazard",
"Spikewheel Acrobat",
"Spinal Centipede",
"Spined Karok",
"Spined Megalodon",
"Spinehorn Minotaur",
"Spinning Wheel",
"Spire Mangler",
"Spire Patrol",
"Spire Winder",
"Spireside Infiltrator",
"Spirit of Malevolence",
"Spirit of the Aldergard",
"Spirit of the Spires",
"Spirit Summoning",
"Spiritual Guardian",
"Spiteful Prankster",
"Spiteful Squad",
"Spitfire Lagac",
"Spitting Earth",
"Splendid Agony",
"Splendor Mare",
"Split the Party",
"Spoils of Adventure",
"Spoils of the Hunt",
"Spontaneous Flight",
"Spore Crawler",
"Spore Swarm",
"Sporeback Wolf",
"Sporecap Spider",
"Sporecrown Thallid",
"Sporemound",
"Spreading Insurrection",
"Spreading Rot",
"Spring /// Mind",
"Springbloom Druid",
"Springjaw Trap",
"Springmane Cervin",
"Springmantle Cleric",
"Sprite Dragon",
"Sprouting Renewal",
"Squad Captain",
"Square Up",
"Squash",
"Squire's Devotion",
"Squirrel Sanctuary",
"Squirrel Sovereign",
"Stab Wound",
"Staggering Insight",
"Stalwart Valkyrie",
"Stampede Rider",
"Stampeding Horncrest",
"Star Pupil",
"Star-Crowned Stag",
"Starlit Mantle",
"Starnheim Aspirant",
"Starnheim Courser",
"Start /// Finish",
"Start from Scratch",
"Startle",
"Startling Development",
"Static Discharge",
"Status // Statue",
"Staunch Shieldmate",
"Steadfast Armasaur",
"Steadfast Paladin",
"Steadfast Sentry",
"Steady Aim",
"Stealth Mission",
"Steelclad Spirit",
"Steelclaw Lance",
"Steelfin Whale",
"Steelform Sliver",
"Steelgaze Griffin",
"Steeple Creeper",
"Sterling Grove",
"Stern Dismissal",
"Steward of Solidarity",
"Stinging Lionfish",
"Stinging Shot",
"Stirring Address",
"Stitched Assistant",
"Stitcher's Supplier",
"Stitchwing Skaab",
"Stolen Vitality",
"Stone Golem",
"Stone Haven Pilgrim",
"Stone Quarry",
"Stone Rain",
"Stonebinder's Familiar",
"Stonebound Mentor",
"Stonerise Spirit",
"Stonework Packbeast",
"Stony Strength",
"Storm Caller",
"Storm Fleet Aerialist",
"Storm Fleet Arsonist",
"Storm Fleet Pyromancer",
"Storm Fleet Sprinter",
"Storm Fleet Spy",
"Storm Fleet Swashbuckler",
"Storm God's Oracle",
"Storm Sculptor",
"Storm Skreelix",
"Storm Strike",
"Storm the Citadel",
"Storm-Kiln Artist",
"Stormchaser Drake",
"Stormrider Spirit",
"Stormwild Capridor",
"Story Seeker",
"Strangling Spores",
"Strategic Planning",
"Street Riot",
"Strength of Solidarity",
"Strength of the Pack",
"Strider Harness",
"Strike It Rich",
"Striking Sliver",
"Striped Bears",
"Striped Riverwinder",
"Stromkirk Bloodthief",
"Stronghold Confessor",
"Struggle /// Survive",
"Struggle for Skemfar",
"Study Break",
"Stuffed Bear",
"Submerged Boneyard",
"Subtle Strike",
"Sudden Breakthrough",
"Sudden Edict",
"Sudden Insight",
"Sudden Spinnerets",
"Suffocating Fumes",
"Sulfurous Mire",
"Sumala Woodshaper",
"Summary Judgment",
"Sun Sentinel",
"Sun-Collared Raptor",
"Sun-Crested Pterodon",
"Sun-Crowned Hunters",
"Sunblade Angel",
"Sunder Shaman",
"Sungold Barrage",
"Sunhome Stalwart",
"Sunlit Hoplite",
"Sunmane Pegasus",
"Sunrise Cavalier",
"Sunrise Seeker",
"Sunscorched Desert",
"Sunscourge Champion",
"Sunset Pyramid",
"Sunset Revelry",
"Supernatural Rescue",
"Supernatural Stamina",
"Supply Caravan",
"Supply Runners",
"Supreme Will",
"Sure Strike",
"Sure-Footed Infiltrator",
"Surge Mare",
"Surtland Frostpyre",
"Survivors' Bond",
"Suspicious Bookcase",
"Sustainer of the Realm",
"Svella, Ice Shaper",
"Swab Goblin",
"Swaggering Corsair",
"Swallow Whole",
"Swamp",
"Swarm Guildmage",
"Swarm of Bloodflies",
"Swarming Goblins",
"Swashbuckling",
"Swathcutter Giant",
"Sweatworks Brawler",
"Sweep Away",
"Sweet Oblivion",
"Swift Response",
"Swift Warden",
"Swiftwater Cliffs",
"Swimmer in Nightmares",
"Swirling Torrent",
"Switcheroo",
"Sworn Companions",
"Sworn Guardian",
"Sylvan Brushstrider",
"Sylvan Ranger",
"Sylvan Shepherd",
"Symmetry Sage",
"Synchronized Spellcraft",
"Synchronized Strike",
"Syncopate",
"Syndicate Guildmage",
"Syndicate Messenger",
"Syphon Essence",
"Syr Alin, the Lion's Claw",
"Syr Carah, the Bold",
"Syr Elenora, the Discerning",
"Syr Faren, the Hengehammer",
"Syr Konrad, the Grim",
"Tactical Advantage",
"Tah-Crop Elite",
"Tajuru Blightblade",
"Tajuru Pathwarden",
"Tajuru Snarecaster",
"Take Heart",
"Take Vengeance",
"Tall as a Beanstalk",
"Talons of Wildwood",
"Talrand's Invocation",
"Tamiyo's Epiphany",
"Tandem Tactics",
"Tangled Florahedron",
"Tangletrap",
"Tapping at the Window",
"Targ Nar, Demon-Fang Gnoll",
"Tattered Mummy",
"Tatyova, Benthic Druid",
"Taunting Arbormage",
"Tavern Ruffian",
"Tavern Swindler",
"Tazeem Raptor",
"Tazeem Roilmage",
"Teach by Example",
"Team Pennant",
"Tectonic Rift",
"Teeterpeak Ambusher",
"Teferi's Protege",
"Teferi's Sentinel",
"Teferi's Time Twist",
"Teferi's Tutelage",
"Tempered Sliver",
"Tempered Veteran",
"Tempest Caller",
"Temple of the Dragon Queen",
"Temple Thief",
"Temporal Machinations",
"Tempting Witch",
"Tenacious Pup",
"Tend the Pests",
"Tendrils of Agony",
"Tendrils of Corruption",
"Tentative Connection",
"Tenth District Guard",
"Tenth District Legionnaire",
"Tenth District Veteran",
"Tenured Inkcaster",
"Tergrid's Shadow",
"Terminal Agony",
"Terramorphic Expanse",
"Terrarion",
"Territorial Boar",
"Territorial Hammerskull",
"Territorial Scythecat",
"Test of Talents",
"Tetsuko Umezawa, Fugitive",
"Teyo, the Shieldmage",
"Teyo's Lightshield",
"Tezzeret's Ambition",
"Tezzeret's Gambit",
"Tezzeret's Strider",
"Tezzeret's Touch",
"Thallid Omnivore",
"Thallid Soothsayer",
"Thaumaturge's Familiar",
"The Binding of the Titans",
"The Birth of Meletis",
"The Eldest Reborn",
"The Flame of Keld",
"The Three Seasons",
"The Trickster-God's Heist",
"The Triumph of Anax",
"The Wanderer",
"Thermo-Alchemist",
"Thicket Crasher",
"Thieves' Tools",
"Thieving Otter",
"Think Twice",
"Thirst for Discovery",
"Thirst for Knowledge",
"Thirst for Meaning",
"Thirsting Bloodlord",
"Thirsting Shade",
"Thopter Arrest",
"Thorn Elemental",
"Thorned Moloch",
"Thornhide Wolves",
"Thornmantle Striker",
"Thornwood Falls",
"Those Who Serve",
"Thought Collapse",
"Thought Distortion",
"Thought Erasure",
"Thoughtbound Phantasm",
"Thraben Exorcism",
"Thraben Inspector",
"Thraben Standard Bearer",
"Thraben Watcher",
"Thrash of Raptors",
"Thrashing Brontodon",
"Threnody Singer",
"Thresher Lizard",
"Thrill of Possibility",
"Thrilling Discovery",
"Thriving Bluff",
"Thriving Grove",
"Thriving Heath",
"Thriving Isle",
"Thriving Moor",
"Thriving Rhino",
"Thriving Turtle",
"Throatseeker",
"Throes of Chaos",
"Thud",
"Thunder Drake",
"Thunderherd Migration",
"Thundering Ceratok",
"Thundering Chariot",
"Thundering Djinn",
"Thundering Rebuke",
"Thundering Sparkmage",
"Thundering Spineback",
"Thunderous Orator",
"Thunderous Snapper",
"Thwart the Enemy",
"Thwart the Grave",
"Tiana, Ship's Caretaker",
"Tibalt, Rakish Instigator",
"Tibalt's Rager",
"Tide Skimmer",
"Tiger-Tribe Hunter",
"Tightening Coils",
"Tilonalli's Crown",
"Tilonalli's Knight",
"Timber Gorge",
"Timberland Guide",
"Time of Ice",
"Timeless Witness",
"Timely Reinforcements",
"Tin Street Cadet",
"Tin Street Dodger",
"Tireless Hauler",
"Tireless Provisioner",
"Tishana's Wayfinder",
"Titanic Brawl",
"Titanic Growth",
"Titanoth Rex",
"Tithebearer Giant",
"Tolarian Kraken",
"Tolarian Scholar",
"Toll of the Invasion",
"Tome Anima",
"Tome Raider",
"Tome Shredder",
"Tomebound Lich",
"Topple the Statue",
"Torch Courier",
"Torch Fiend",
"Torment of Scarabs",
"Tormenting Voice",
"Tormentor's Helm",
"Tormod's Crypt",
"Totally Lost",
"Tourach's Canticle",
"Tournament Grounds",
"Tower Defense",
"Towering-Wave Mystic",
"Toxic Scorpion",
"Track Down",
"Tragic Poet",
"Trail of Crumbs",
"Traitorous Greed",
"Tranquil Cove",
"Tranquil Expanse",
"Tranquil Thicket",
"Transcendent Envoy",
"Trapped in the Tower",
"Trash for Treasure",
"Traveler's Amulet",
"Traveling Minister",
"Treasure Hunt",
"Treasure Keeper",
"Treetop Warden",
"Trelasarra, Moon Dancer",
"Trespasser's Curse",
"Trial of Ambition",
"Trial of Knowledge",
"Trial of Solidarity",
"Trial of Strength",
"Trial of Zeal",
"Trickster's Talisman",
"Triton Waverider",
"Triumph of Gerrard",
"Triumphant Surge",
"Trollbred Guardian",
"Trophy Mage",
"Trove of Temptation",
"True Love's Kiss",
"Truefire Captain",
"Trufflesnout",
"Trumpet Blast",
"Trumpeting Gnarr",
"Trumpeting Herd",
"Trusted Pegasus",
"Trusty Packbeast",
"Trusty Retriever",
"Tuinvale Treefolk",
"Tuktuk Rubblefort",
"Turn into a Pumpkin",
"Turn the Earth",
"Turn to Slag",
"Turntimber Ascetic",
"Turret Ogre",
"Tuskeri Firewalker",
"Twilight Panther",
"Twin-Silk Spider",
"Twinblade Assassins",
"Twinblade Geist",
"Twinblade Paladin",
"Twinscroll Shaman",
"Two-Headed Zombie",
"Tymaret, Chosen from Death",
"Typhoid Rats",
"Tyrant's Scorn",
"Ugin's Conjurant",
"Ulvenwald Mysteries",
"Umara Mystic",
"Umara Wizard",
"Umbral Juke",
"Unblinking Observer",
"Unbreakable Bond",
"Unbridled Growth",
"Unburden",
"Unburial Rites",
"Uncaged Fury",
"Unchained Berserker",
"Unclaimed Territory",
"Uncomfortable Chill",
"Unconventional Tactics",
"Undead Augur",
"Undead Butler",
"Undead Servant",
"Undercity Necrolisk",
"Undercity Scavenger",
"Undercity Uprising",
"Undercity's Embrace",
"Underdark Basilisk",
"Underhanded Designs",
"Undersea Invader",
"Underworld Charger",
"Underworld Dreams",
"Underworld Fires",
"Underworld Rage-Hound",
"Undying Malice",
"Unexpected Fangs",
"Unexpected Windfall",
"Unexplained Disappearance",
"Unexplained Vision",
"Unfriendly Fire",
"Unhallowed Phalanx",
"Unholy Heat",
"Unholy Indenture",
"Unholy Officiant",
"Universal Automaton",
"Universal Solvent",
"Unknown Shores",
"Unleash Fury",
"Unlicensed Disintegration",
"Unlikely Aid",
"Unnatural Moonrise",
"Unquenchable Thirst",
"Unruly Mob",
"Unstable Obelisk",
"Unsubstantiate",
"Unsummon",
"Untamed Kavu",
"Untethered Express",
"Unwilling Ingredient",
"Unwind",
"Urban Daggertooth",
"Urban Utopia",
"Urgoros, the Empty One",
"Ursine Champion",
"Urza's Rage",
"Urza's Tome",
"Usher of the Fallen",
"Utility Knife",
"Valduk, Keeper of the Flame",
"Valiant Rescuer",
"Valkyrie's Sword",
"Valor of the Worthy",
"Valor Singer",
"Valorous Stance",
"Valorous Steed",
"Vampire Champion",
"Vampire Interloper",
"Vampire Neonate",
"Vampire of the Dire Moon",
"Vampire Opportunist",
"Vampire Revenant",
"Vampire Slayer",
"Vampire Socialite",
"Vampire Sovereign",
"Vampire Spawn",
"Vampire's Kiss",
"Vampire's Zeal",
"Vampires' Vengeance",
"Vanquish the Weak",
"Vantress Paladin",
"Vastwood Fortification",
"Vastwood Surge",
"Vastwood Zendikon",
"Vault Robber",
"Vault Skirge",
"Vedalken Entrancer",
"Vedalken Mesmerist",
"Vega, the Watcher",
"Veiled Shade",
"Venerable Knight",
"Vengeful Reaper",
"Vengeful Rebel",
"Vengeful Strangler",
"Vengeful Warchief",
"Venomous Changeling",
"Venomous Hierophant",
"Verdant Rebirth",
"Vermin Gorger",
"Vernadi Shieldmate",
"Vesperlark",
"Veteran Adventurer",
"Veteran Charger",
"Veteran Dungeoneer",
"Veteran Motorist",
"Vexing Gull",
"Vial of Dragonfire",
"Viashino Lashclaw",
"Viashino Pyromancer",
"Vicious Conquistador",
"Vicious Offering",
"Vicious Rumors",
"Vigilant Baloth",
"Vigorspore Wurm",
"Vile Manifestation",
"Vilespawn Spider",
"Village Rites",
"Village Watch",
"Vindictive Vampire",
"Vine Gecko",
"Vine Mare",
"Vineshaper Mystic",
"Virulent Plague",
"Visionary Augmenter",
"Vivien's Crocodile",
"Vivien's Grizzly",
"Vivien's Jaguar",
"Vivisection",
"Vizier of Deferment",
"Vizier of Remedies",
"Vizier of the Anointed",
"Vizier of the Scorpion",
"Vizier of Tumbling Sands",
"Vizkopa Vampire",
"Vodalian Arcanist",
"Voice of the Provinces",
"Void Beckoner",
"Volatile Fjord",
"Volcanic Dragon",
"Volcanic Fallout",
"Volcanic Geyser",
"Voldaren Ambusher",
"Voldaren Epicure",
"Voldaren Stinger",
"Volley Veteran",
"Voltaic Brawler",
"Voltaic Servant",
"Voltaic Visionary",
"Voracious Typhon",
"Voracious Vampire",
"Vorstclaw",
"Vortex Runner",
"Voyage's End",
"Vraska, Swarm's Eminence",
"Vraska's Conquistador",
"Vraska's Finisher",
"Vryn Wingmare",
"Vulpikeet",
"Wailing Ghoul",
"Waker of Waves",
"Walk the Plank",
"Walking Corpse",
"Wall of Blossoms",
"Wall of Forgotten Pharaohs",
"Wall of Lost Thoughts",
"Wall of Mist",
"Wall of One Thousand Cuts",
"Wall of Runes",
"Wall of Vines",
"Wand of Vertebrae",
"Wander in Death",
"Wanderer's Strike",
"Wandering Mind",
"Wandering Troubadour",
"Wanderlight Spirit",
"Wandermare",
"Wanted Scoundrels",
"War Screecher",
"Warbriar Blessing",
"Warchanter Skald",
"Warcry Phoenix",
"Warded Battlements",
"Warden of Evos Isle",
"Warden of the Chained",
"Warden of the Woods",
"Wardscale Crocodile",
"Warfire Javelineer",
"Warhorn Blast",
"Warlock Class",
"Warlord's Fury",
"Warmonger's Chariot",
"Warteye Witch",
"Wary Okapi",
"Wash Away",
"Wasp of the Bitter End",
"Wasteland Scorpion",
"Watcher in the Mist",
"Watcher of the Spheres",
"Watchers of the Dead",
"Watchful Giant",
"Watchful Naga",
"Waterfall Aerialist",
"Waterkin Shaman",
"Waterknot",
"Watertrap Weaver",
"Wavesifter",
"Wayward Servant",
"Weapon Rack",
"Weaponcraft Enthusiast",
"Weaponize the Monsters",
"Weary Prisoner",
"Weaselback Redcap",
"Weather the Storm",
"Weathered Runestone",
"Weaver of Blossoms",
"Weaver of Lightning",
"Webweaver Changeling",
"Wedding Invitation",
"Wedding Security",
"Wee Dragonauts",
"Weigh Down",
"Weight of Memory",
"Weldfast Engineer",
"Weldfast Monitor",
"Weldfast Wingsmith",
"Welding Sparks",
"Whirler Rogue",
"Whirler Virtuoso",
"Whirlermaker",
"Whirlwind Denial",
"Whisper Agent",
"Whisper Squad",
"Whisper, Blood Liturgist",
"Whispering Snitch",
"Whispering Wizard",
"White Dragon",
"Wicked Guardian",
"Wight of Precinct Six",
"Wild Ceratok",
"Wild Onslaught",
"Wild Shape",
"Wild Wanderer",
"Wildfire Elemental",
"Wildgrowth Walker",
"Wildheart Invoker",
"Wildsize",
"Wildwood Patrol",
"Wildwood Scourge",
"Wildwood Tracker",
"Will of the All-Hunter",
"Wilt",
"Wily Goblin",
"Wind Strider",
"Wind-Kin Raiders",
"Wind-Scarred Crag",
"Windcaller Aven",
"Windgrace Acolyte",
"Winding Constrictor",
"Winding Way",
"Windrider Wizard",
"Winds of Rebuke",
"Windstorm Drake",
"Winged Shepherd",
"Winged Words",
"Wingfold Pteron",
"Wings of Hubris",
"Wings of the Cosmos",
"Wingspan Mentor",
"Wingsteed Trainer",
"Wintermoor Commander",
"Winterthorn Blessing",
"Wishcoin Crab",
"Wishful Merfolk",
"Wispweaver Angel",
"Witch's Cauldron",
"Witch's Cottage",
"Witch's Familiar",
"Witch's Oven",
"Witch's Web",
"Witching Well",
"Witherbloom Apprentice",
"Witherbloom Campus",
"Witherbloom Pledgemage",
"Withercrown",
"Witness of Tomorrows",
"Witness the Future",
"Wizard Class",
"Wizard's Lightning",
"Wizard's Retort",
"Wojek Bodyguard",
"Wolf Strike",
"Wolf's Quarry",
"Wolfkin Bond",
"Wolfkin Outcast",
"Wolfrider's Saddle",
"Wolfwillow Haven",
"Wonder",
"Woodborn Behemoth",
"Woodland Champion",
"Woodland Chasm",
"Woodland Mystic",
"Woodland Stream",
"Woodweaver's Puzzleknot",
"Workshop Assistant",
"Worldsoul Colossus",
"Wormhole Serpent",
"Wrap in Flames",
"Wrecking Beast",
"Wren's Run Hydra",
"Wren's Run Vanquisher",
"Wretched Throng",
"Yargle, Glutton of Urborg",
"Yarok's Fenlurker",
"Yarok's Wavecrasher",
"Yavimaya Sapherd",
"Yoked Ox",
"Yoked Plowbeast",
"You Come to a River",
"You Come to the Gnoll Camp",
"You Find a Cursed Idol",
"You Find Some Prisoners",
"You Find the Villains' Lair",
"You Happen On a Glade",
"You Hear Something on Watch",
"You Meet in a Tavern",
"You See a Guard Approach",
"You See a Pair of Goblins",
"You're Ambushed on the Road",
"Young Necromancer",
"Young Pyromancer",
"Youthful Knight",
"Youthful Valkyrie",
"Yuan-Ti Fang-Blade",
"Zagoth Crystal",
"Zagoth Mamba",
"Zealot of the God-Pharaoh",
"Zendikar's Roil",
"Zenith Flare",
"Zephyr Boots",
"Zephyr Charge",
"Zephyr Gull",
"Zhalfirin Decoy",
"Zhalfirin Void",
"Zhur-Taa Goblin",
"Zimone, Quandrix Prodigy",
"Zof Consumption",
"Zombie Infestation",
"Zombie Ogre",
"Zulaport Duelist",
];